wellFoundedDevelopers/Algorithm

- src/main/kotlin/hyunsoo/1week/test.kt
- src/main/kotlin/jimin/4week/그림.kt
- src/main/kotlin/jimin/5week/가로수.kt
- src/main/kotlin/jimin/5week/랜선 자르기.kt
- src/main/kotlin/jimin/5week/바닥 장식.kt
- src/main/kotlin/jimin/5week/빙고.kt
- src/main/kotlin/jimin/5week/킹.kt
```
킹: ✅
바닥 장식: ✅
빙고: ✅
랜선 자르기: ✅
가로수: ✅
```
```
```
> [이지민] 킹, 바닥 장식, 빙고, 랜선 자르기, 가로수

- src/main/kotlin/heejik/5week/가로수.kt
- src/main/kotlin/heejik/5week/랜선 자르기.kt
- src/main/kotlin/heejik/5week/바닥 장식.kt
- src/main/kotlin/heejik/5week/빙고.kt
- src/main/kotlin/heejik/5week/킹.kt
```
킹: ✅
바닥 장식: ✅
빙고: ✅
랜선 자르기: ✅
가로수: ✅
```
- 오랜만에 이분탐색이랑, 최대공약수 구하는 알고리즘을 부딪혀서 애먹었네요..
- 킹 문제와 같이 기본적인 2*2 배열의 index 순서와 반대인 친구는 힘드네요..
> [장희직] 킹, 바닥 장식, 빙고, 랜선 자르기, 가로수

- src/main/kotlin/byeonghee/6week/근손실.kt
- src/main/kotlin/byeonghee/6week/비슷한 단어.kt
- src/main/kotlin/byeonghee/6week/아기 상어 2.kt
- src/main/kotlin/byeonghee/6week/트리의 부모 찾기.kt
- src/main/kotlin/byeonghee/6week/회의실 배정.kt
```
근손실: ✅
비슷한 단어: ✅
아기상어2: ✅
트리의 부모 찾기: ✅
회의실 배정: ✅
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---
> [소병희] 근손실, 비슷한 단어, 아기상어2, 트리의 부모 찾기, 회의실 배정

- src/main/kotlin/heejik/7week/미로 만들기.kt
- src/main/kotlin/heejik/7week/차이를 최대로.kt
- src/main/kotlin/heejik/7week/최소 힙.kt
- src/main/kotlin/heejik/7week/한 줄로 서기.kt
- src/main/kotlin/heejik/7week/흙길 보수하기.kt
```
최소 힙: ✅
차이를 최대로: ✅
흙길 보수하기: ✅
한 줄로 서기: ✅
미로 만들기: ✅
```
> [장희직] 최소 힙, 차이를 최대로, 흙길 보수하기, 한 줄로 서기, 미로 만들기

- src/main/kotlin/heejik/9week/1, 2, 3 더하기 4.kt
- src/main/kotlin/heejik/9week/Java vs C++.kt
- src/main/kotlin/heejik/9week/도어맨.kt
- src/main/kotlin/heejik/9week/배열 복원하기.kt
- src/main/kotlin/heejik/9week/후위 표기식2.kt
```
Java vs C++: ✅
1,2,3 더하기 4: ⛔️
도어맨: ✅
배열 복원하기: ✅
후위 표기식2: ✅
```
> [장희직] Java vs C++, 1,2,3 더하기 4, 도어맨, 배열 복원하기, 후위 표기식2

- src/main/kotlin/byeonghee/9week/1 2 3 더하기 4.kt
- src/main/kotlin/byeonghee/9week/Java vs C++.kt
- src/main/kotlin/byeonghee/9week/도어맨.kt
- src/main/kotlin/byeonghee/9week/배열 복원하기.kt
- src/main/kotlin/byeonghee/9week/후위 표기식2.kt
```
Java vs C++: ✅
1,2,3 더하기 4: ⛔️(답 참고)
도어맨: ✅
배열 복원하기: ✅
후위 표기식2: ✅
```
> [소병희] Java vs C++, 1,2,3 더하기 4, 도어맨, 배열 복원하기, 후위 표기식2

- src/main/kotlin/hyunsoo/12week/그룹 단어 체커.kt
- src/main/kotlin/hyunsoo/12week/수리공 항승.kt
- src/main/kotlin/hyunsoo/12week/트럭.kt
```
그룹 단어 체커: ✅
수리공 항승: ✅
트럭: ✅
안녕: ❎
```
- [문제](링크)
- [문제](링크)
- Dp... 진짜 어떻게 풀죠...
---
> [전현수]  그룹 단어 체커, 수리공 항승, 트럭

- src/main/kotlin/hyunsoo/13week/DNA.kt
- src/main/kotlin/hyunsoo/13week/기적의 매매법.kt
- src/main/kotlin/hyunsoo/13week/두 수의 합.kt
- src/main/kotlin/hyunsoo/13week/두 용액.kt
- src/main/kotlin/hyunsoo/13week/등수 구하기.kt
- src/main/kotlin/hyunsoo/13week/배열 합치기.kt
- src/main/kotlin/hyunsoo/13week/부분합.kt
- src/main/kotlin/hyunsoo/13week/소수의 연속합.kt
- src/main/kotlin/hyunsoo/13week/수 이어 쓰기 1.kt
- src/main/kotlin/hyunsoo/13week/수들의 합 2.kt
- src/main/kotlin/hyunsoo/13week/수들의 합 5.kt
- src/main/kotlin/hyunsoo/13week/수열.kt
- src/main/kotlin/hyunsoo/13week/주몽.kt
```
기적의 매매법: ✅
수 이어 쓰기 1: ✅
등수 구하기: ✅
DNA: ⛔️
```
- [수들의 합 2](https://www.acmicpc.net/problem/2003)
- [소수의 연속합](https://www.acmicpc.net/problem/1644)
- [수열](https://www.acmicpc.net/problem/2559)
- [두 용액](https://www.acmicpc.net/problem/2470)
- [두 수의 합](https://www.acmicpc.net/problem/3273)
- [배열 합치기](https://www.acmicpc.net/problem/11728)
- [수들의 합 5](https://www.acmicpc.net/problem/2018)
- [주몽](https://www.acmicpc.net/problem/1940)
- [부분합](https://www.acmicpc.net/problem/1806)
- DNA 문제를 이해 못해서 정말 시간을 많이 버렸습니다.... 제 문해력이 딸리는 건지...
혹시 저 같으신 분이 있으실까봐 문제의 이해를 위해 참고한 블로그 링크 남겨봅니다!!! (구현 자체는 쉬웠어용)
[DNA 문제 이해가 안되어서 참고한 곳](https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=occidere&logNo=220857781286)
- 투 포인터 연습할라고 문제 조금 더 풀었슴다..
---
> [전현수] 기적의 매매법, 수 이어 쓰기 1, 등수 구하기, DNA

- src/main/kotlin/heejik/12week/안녕.kt
- src/main/kotlin/heejik/12week/트럭.kt
- src/main/kotlin/heejik/13week/DNA.kt
- src/main/kotlin/heejik/13week/등수 구하기.kt
- src/main/kotlin/heejik/13week/수 이어 쓰기 1.kt
- src/main/kotlin/heejik/13week/시계.kt
- src/main/kotlin/heejik/13week/크로스워드.kt
- src/main/kotlin/heejik/13week/🐜 기적의 매매법 🐜.kt
```
기적의 매매법: ✅
수 이어 쓰기 1: ✅
등수 구하기: ✅
DNA: ✅
```
- [크로스워드](https://www.acmicpc.net/problem/1706)
- [시계](https://www.acmicpc.net/problem/2082)
> [장희직] 기적의 매매법, 수 이어 쓰기 1, 등수 구하기, DNA

- src/main/kotlin/jimin/13week/DNA.kt
- src/main/kotlin/jimin/13week/기적의 매매법.kt
- src/main/kotlin/jimin/13week/등수 구하기.kt
- src/main/kotlin/jimin/13week/수 이어 쓰기1.kt
```
기적의 매매법: ✅
수 이어 쓰기 1: ✅
등수 구하기: ✅
DNA: ✅
```
```
```
> [이지민] 기적의 매매법, 수 이어 쓰기 1, 등수 구하기, DNA

- src/main/kotlin/byeonghee/20week/별자리 만들기.kt
- src/main/kotlin/byeonghee/20week/안전 영역.kt
- src/main/kotlin/byeonghee/20week/양.kt
- src/main/kotlin/byeonghee/20week/에너지 모으기.kt
```
양: ✅
별자리 만들기: ✅
에너지 모으기: ⛔
안전 영역: ✅
```
> [소병희] 양, 별자리 만들기, 에너지 모으기, 안전 영역

- src/main/kotlin/jimin/23week/로봇 청소기.kt
- src/main/kotlin/jimin/23week/보물섬.kt
- src/main/kotlin/jimin/23week/센서.kt
- src/main/kotlin/jimin/23week/합분해.kt
```
로봇 청소기: ✅
보물섬: ✅ 
센서: ✅ 
합분해: ⛔️
```
> [이지민] 로봇 청소기, 보물섬, 센서, 합분해

- src/main/kotlin/heejik/24week/도서관.kt
- src/main/kotlin/heejik/25week/감시.kt
- src/main/kotlin/heejik/25week/선수과목.kt
- src/main/kotlin/heejik/26week/맥주 마시면서 걸어가기.kt
- src/main/kotlin/heejik/26week/절댓값 힙.kt
- src/main/kotlin/heejik/26week/치즈.kt
- src/main/kotlin/heejik/26week/치킨 배달.kt
- src/main/kotlin/heejik/26week/표현 가능한 이진트리.kt
```
표현 가능한 이진트리: ✅
절댓값 힙: ✅
치즈: ⛔️
치킨 배달: ✅
```
- [맥주 마시면서 걸어가기](https://www.acmicpc.net/problem/9205)
```
맥주 마시면서 걸어가기: 👍  문제 유형을 파악하는 게 관건이라 생각합니다!
```
> [장희직] 표현 가능한 이진트리, 절댓값 힙, 치즈, 치킨 배달

- src/main/kotlin/byeonghee/week26/절댓값 힙.kt
- src/main/kotlin/byeonghee/week26/치즈.kt
- src/main/kotlin/byeonghee/week26/치킨 배달.kt
- src/main/kotlin/byeonghee/week26/표현 가능한 이진트리.kt
```
표현 가능한 이진트리: ✅
절댓값 힙: ✅
치즈: ✅
치킨 배달: ✅
```
> [소병희] 표현 가능한 이진트리, 절댓값 힙, 치즈, 치킨 배달

- src/main/kotlin/hyunsoo/28week/드래곤 커브.kt
- src/main/kotlin/hyunsoo/28week/미세먼지 안녕!.kt
- src/main/kotlin/hyunsoo/28week/연구소.kt
- src/main/kotlin/hyunsoo/28week/친구비.kt
```
연구소: ✅
친구비: ✅
드래곤 커브: ⛔️
미세먼지 안녕!: ✅
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
삼성문제 진짜 토나오네요...
- 2차원 좌표를 넘 헷갈리게 줘가지고... 문제를 제대로 안 읽는 제 탓이겟죠,,,
---
> [전현수] - 연구소, 친구비, 드래곤 커브, 미세먼지 안녕

- src/main/kotlin/byeonghee/week28/드래곤커브.kt
- src/main/kotlin/byeonghee/week28/미세먼지안녕.kt
- src/main/kotlin/byeonghee/week28/연구소.kt
- src/main/kotlin/byeonghee/week28/친구비.kt
```
연구소: ✅
미세먼지 안녕!: ✅
친구비: ✅
드래곤 커브: ✅
```
> [소병희] 연구소, 미세먼지 안녕!, 친구비, 드래곤 커브

- src/main/kotlin/byeonghee/week43/겹치는 건 싫어.kt
- src/main/kotlin/byeonghee/week43/쉬운 최단거리.kt
- src/main/kotlin/byeonghee/week43/회전 초밥.kt
```
겹치는 건 싫어: ✅
쉬운 최단거리: ✅
회전 초밥: ✅
기타리스트: ❎
```
> [소병희] 겹치는 건 싫어, 쉬운 최단거리, 회전 초밥

- src/main/kotlin/jimin/43week/겹치는 건 싫어.py
- src/main/kotlin/jimin/43week/기타리스트.py
- src/main/kotlin/jimin/43week/쉬운 최단거리.py
- src/main/kotlin/jimin/43week/회전초밥.py
```
겹치는 건 싫어: ⛔️
기타리스트: ⛔️
회전초밥: ✅
쉬운 최단거리: ✅
```
> [이지민] - 겹치는 건 싫어, 기타리스트, 회전초밥, 쉬운 최단거리

- src/main/kotlin/hyunsoo/43week/겹치는 건 싫어.kt
- src/main/kotlin/hyunsoo/43week/기타리스트.kt
- src/main/kotlin/hyunsoo/43week/쉬운 최단거리.kt
- src/main/kotlin/hyunsoo/43week/회전 초밥.kt
```
쉬운 최단거리: ✅
겹치는 건 싫어: ⛔️
기타리스트: ⛔️
회전 초밥: ✅
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---
> [전현수] - 쉬운 최단거리, 겹치는 건 싫어, 기타리스트, 회전 초밥

- src/main/kotlin/heejik/43week/겹치는 건 싫어.kt
- src/main/kotlin/heejik/43week/기타리스트.kt
- src/main/kotlin/heejik/43week/쉬운 최단거리.kt
- src/main/kotlin/heejik/43week/회전 초밥.kt
```
겹치는 건 싫어: ✅
쉬운 최단거리: ✅
회전 초밥: ✅
기타리스트: ⛔️
```
`기타리스트..........`
> [장희직] - 겹치는 건 싫어, 쉬운 최단거리, 회전 초밥, 기타리스트

- src/main/kotlin/hyunsoo/44week/CCW.kt
- src/main/kotlin/hyunsoo/44week/전구와 스위치.kt
- src/main/kotlin/hyunsoo/44week/케빈 베이컨의 6단계 법칙.kt
- src/main/kotlin/hyunsoo/44week/함께 블록 쌓기.kt
```
케빈 베이컨의 6단계 법칙: ✅
함께 블록 쌓기: ⛔️
전구와 스위치: ⛔️
CCW: ⛔️
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---
> [전현수] - 케빈 베이컨의 6단계 법칙, 함께 블록 쌓기, 전구와 스위치, CCW

- src/main/kotlin/byeonghee/week43/기타리스트.kt
- src/main/kotlin/byeonghee/week44/CCW.kt
- src/main/kotlin/byeonghee/week44/전구와 스위치.kt
- src/main/kotlin/byeonghee/week44/케빈 베이컨의 6단계 법칙.kt
- src/main/kotlin/byeonghee/week44/함께 블록 쌓기.kt
```
케빈 베이컨의 6단계 법칙: ✅
전구와 스위치: ⛔️
CCW: ⛔️
함께 블록 쌓기: ✅
```
> [소병희] 케빈 베이컨의 6단계 법칙, 전구와 스위치, CCW, 함께 블록 쌓기

- src/main/kotlin/heejik/44week/CCW.kt
- src/main/kotlin/heejik/44week/전구와 스위치.kt
- src/main/kotlin/heejik/44week/케빈 베이컨의 6단계 법칙.kt
- src/main/kotlin/heejik/44week/함께 블록 쌓기.kt
```
케빈 베이컨의 6단계 법칙: ✅
전구와 스위치: ✅
CCW: ⛔️
함께 블록 쌓기: ✅
```
CCW?
> [장희직] - 케빈 베이컨의 6단계 법칙, 전구와 스위치, CCW, 함께 블록 쌓기

- src/main/kotlin/heejik/45week/A와 B.kt
- src/main/kotlin/heejik/45week/게임.kt
- src/main/kotlin/heejik/45week/연산자 끼워넣기.kt
```
게임: ✅
연산자 끼워넣기: ✅
디스크 컨트롤러: ✅
A와 B: ✅
```
> [장희직] - 게임, 연산자 끼워넣기, 디스크 컨트롤러, A와 B

- src/main/kotlin/byeonghee/week45/A와 B.kt
- src/main/kotlin/byeonghee/week45/게임.kt
- src/main/kotlin/byeonghee/week45/연산자 끼워넣기.kt
- src/main/kotlin/byeonghee/week46/경주로건설.kt
- src/main/kotlin/byeonghee/week46/농장 관리.kt
- src/main/kotlin/byeonghee/week46/빌런호석.kt
- src/main/kotlin/byeonghee/week46/숨바꼭질3.kt
```
숨바꼭질3: ✅
농장 관리: ❎
경주로 건설: ❎
빌런  호석: ❎
```
ㅠㅠㅠ 이렇게 못풀어오다니....죄송해유😭
> [소병희] 숨바꼭질3

- src/main/kotlin/hyunsoo/47week/A와 B 2.kt
- src/main/kotlin/hyunsoo/47week/알고스팟.kt
- src/main/kotlin/hyunsoo/47week/입국심사.kt
- src/main/kotlin/hyunsoo/47week/회장뽑기.kt
```
알고스팟: ✅
A와 B 2: ⛔️
입국심사: ⛔️
회장뽑기: ✅
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---
> [전현수] - 알고스팟, A와 B 2, 입국심사, 회장뽑기

- src/main/kotlin/byeonghee/week47/A와 B 2.kt
- src/main/kotlin/byeonghee/week47/알고스팟.kt
- src/main/kotlin/byeonghee/week47/입국심사.kt
- src/main/kotlin/byeonghee/week47/회장뽑기.kt
```
알고스팟: ✅
A와 B 2: ✅
회장뽑기: ✅
입국심사: ⛔
```
> [소병희] 알고스팟, A와 B 2, 회장뽑기, 입국심사

- src/main/kotlin/jimin/47week/A와 B 2.py
- src/main/kotlin/jimin/47week/알고스팟.py
- src/main/kotlin/jimin/47week/입국심사.py
- src/main/kotlin/jimin/47week/회장뽑기.py
```
알고스팟: ✅
A와 B 2: ⛔️
회장뽑기: ✅
입국심사: ✅
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
> [이지민] - A와 B 2, 알고스팟, 회장뽑기, 입국심사

- src/main/kotlin/jimin/48week/백도어.py
- src/main/kotlin/jimin/48week/순위.py
- src/main/kotlin/jimin/48week/주차장.py
```
주차장: ✅
순위: ⛔️
백도어: ⛔️
탐: ❎
```
> [이지민] - 주차장, 순위, 백도어

- src/main/kotlin/heejik/48week/백도어.kt
- src/main/kotlin/heejik/48week/순위.kt
- src/main/kotlin/heejik/48week/주차장.kt
- src/main/kotlin/heejik/48week/탑.kt
> [장희직] - 주차장, 순위, 탑

- src/main/kotlin/hyunsoo/48week/백도어.kt
- src/main/kotlin/hyunsoo/48week/순위.kt
- src/main/kotlin/hyunsoo/48week/주차장.kt
- src/main/kotlin/hyunsoo/48week/탑.kt
```
백도어: ✅
주차장: ✅
순위: ⛔️
탑: ✅
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---
> [전현수] - 백도어, 주차장, 순위, 탑

- src/main/kotlin/byeonghee/week48/백도어.kt
- src/main/kotlin/byeonghee/week48/주차장.kt
- src/main/kotlin/byeonghee/week48/탑.kt
```
탑: ✅
주차장: ✅
백도어: ✅
순위: ❎
```
> [소병희] 백도어, 탑, 주차장

- src/main/kotlin/heejik/48week/백도어.kt
- src/main/kotlin/heejik/49week/노드사이의 거리.kt
- src/main/kotlin/heejik/49week/벼락치기.kt
- src/main/kotlin/heejik/49week/빗물.kt
- src/main/kotlin/heejik/49week/할인 행사.kt
```
노드사이의 거리: ✅
빗물: ✅
벼락치기: ⛔️
할인 행사: ✅
```
> [장희직] - 노드사이의 거리, 빗물, 벼락치기, 할인 행사

- src/main/kotlin/hyunsoo/49week/노드사이의 거리.kt
- src/main/kotlin/hyunsoo/49week/벼락치기.kt
- src/main/kotlin/hyunsoo/49week/빗물.kt
- src/main/kotlin/hyunsoo/49week/할인 행사.kt
```
노드사이의 거리: ✅
빗물: ⛔️
벼락치기: ⛔️
할인 행사: ✅
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---
> [전현수] - 노드사이의 거리, 빗물, 벼락치기, 할인 행사

- src/main/kotlin/jimin/49week/노드사이의 거리.py
- src/main/kotlin/jimin/49week/벼락치기.py
- src/main/kotlin/jimin/49week/빗물.py
- src/main/kotlin/jimin/49week/할인 행사.py
- src/main/kotlin/jimin/50week/북쪽나라의 도로.py
- src/main/kotlin/jimin/50week/숫자고르기.py
- src/main/kotlin/jimin/50week/연구소2.py
```
북쪽나라의 도로: ⛔️
숫자고르기: ⛔️
연구소2: ✅
```
> [이지민] - 북쪽나라의 도로, 숫자고르기, 연구소2

- src/main/kotlin/hyunsoo/50week/두 큐 합 같게 만들기.kt
- src/main/kotlin/hyunsoo/50week/북쪽나라의 도로.kt
- src/main/kotlin/hyunsoo/50week/숫자고르기.kt
- src/main/kotlin/hyunsoo/50week/연구소 2.kt
```
연구소 2: ✅
두 큐 합 같게 만들기: ⛔️
숫자고르기: ⛔️
북쪽나라의 도로: ⛔️
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---
> [전현수] - 연구소 2, 두 큐 합 같게 만들기, 숫자고르기, 북쪽나라의 도로

- src/main/kotlin/heejik/50week/두 큐 합 같게 만들기.kt
- src/main/kotlin/heejik/50week/북쪽나라의 도로.kt
- src/main/kotlin/heejik/50week/숫자고르기.kt
- src/main/kotlin/heejik/50week/연구소 2.kt
```
연구소 2: ⛔️
두 큐 합 같게 만들기: ✅
숫자고르기: ✅
북쪽나라의 도로: ⛔️
```
> [장희직] - 연구소 2, 두 큐 합 같게 만들기, 숫자고르기, 북쪽나라의 도로

- src/main/kotlin/jimin/51week/민겸 수.kt
- src/main/kotlin/jimin/51week/이모티콘 할인 행사.kt
> [이지민] - 민겸 수, 이모티콘 할인 행사

- src/main/kotlin/heejik/51week/k진수에서 소수 개수 구하기.kt
- src/main/kotlin/heejik/51week/거리두기 확인하기.kt
- src/main/kotlin/heejik/51week/거리두기 확인하기2.kt
- src/main/kotlin/heejik/51week/민겸 수.kt
- src/main/kotlin/heejik/51week/양궁대회.kt
- src/main/kotlin/heejik/51week/이모티콘 할인행사.kt
- src/main/kotlin/heejik/51week/주차 요금 계산.kt
```
민겸 수: ✅
이모티콘 할인 행사: ✅
```
- [문제](링크)
- [문제](링크)
> [장희직] - 민겸 수, 이모티콘 할인 행사

- src/main/kotlin/byeonghee/week51/민겸 수.kt
- src/main/kotlin/byeonghee/week51/소가 길을 건너간 이유.kt
- src/main/kotlin/byeonghee/week51/영상처리.kt
- src/main/kotlin/byeonghee/week51/이모티콘 할인행사.kt
```
민겸 수: ✅
이모티콘 할인행사: ✅
영상처리: ✅
```
- [소가 길을 건너간 이유 1](https://www.acmicpc.net/problem/14467)
> [소병희] - 민겸 수, 이모티콘 할인행사, 영상처리

- src/main/kotlin/heejik/52week/222-폴링.kt
- src/main/kotlin/heejik/52week/N번째 큰 수.kt
- src/main/kotlin/heejik/52week/도넛과 막대 그래프.kt
- src/main/kotlin/heejik/52week/도넛과 막대 그래프2.kt
- src/main/kotlin/heejik/52week/종이의 개수.kt
- src/main/kotlin/heejik/52week/택배 배달과 수거하기.kt
```
N번째 큰 수: ✅
종이의 개수: ✅
택배 배달과 수거하기 ⛔️
222-폴링 : ✅
```
- [도넛과 막대 그래프](https://school.programmers.co.kr/learn/courses/30/lessons/258711): 👍
> [장희직] - N번째 큰 수, 종이의 개수, 택배 배달과 수거하기, 222-폴링 

- src/main/kotlin/jimin/week52/N번째_큰_수.java
- src/main/kotlin/jimin/week52/종이의 개수.kt
- src/main/kotlin/jimin/week52/택배_배달과_수거하기.java
- src/main/kotlin/jimin/week52/풀링.java
```
222-풀링: ✅
종이의 개수: ✅
N번째 큰 수: ✅
택배 배달과 수거하기: ✅
> [이지민] - 222-풀링, 종이의 개수, N번째 큰 수, 택배 배달과 수거하기

- src/main/kotlin/jimin/53week/구간 합 구하기 5.py
- src/main/kotlin/jimin/53week/도넛과 막대 그래프.py
- src/main/kotlin/jimin/53week/작업.py
- src/main/kotlin/jimin/53week/키 순서.py
```
구간 합 구하기 5: ✅
작업: ✅
도넛과 막대 그래프: ✅
키 순서: ❎
```
> [이지민] - 구간 합 구하기 5, 작업, 도넛과 막대 그래프

- src/main/kotlin/heejik/53week/구간 합 구하기 5.kt
- src/main/kotlin/heejik/53week/서강그라운드.kt
- src/main/kotlin/heejik/53week/작업.kt
- src/main/kotlin/heejik/53week/키 순서.kt
```
작업: ✅
키 순서: ⛔️
구간 합 구하기 5: ✅
도넛과 막대 그래프: ✅
```
> [장희직] - 작업, 키 순서, 구간 합 구하기 5, 도넛과 막대 그래프

- src/main/kotlin/byeonghee/week53/구간 합 구하기 5.kt
- src/main/kotlin/byeonghee/week53/도넛과 막대 그래프.kt
- src/main/kotlin/byeonghee/week53/작업.kt
- src/main/kotlin/byeonghee/week53/키 순서.kt
```
작업: ✅
구간 합 구하기 5: ✅
키 순서: ⛔️
도넛과 막대 그래프: ⛔️
```
> [소병희] - 작업, 키 순서, 구간 합 구하기 5, 도넛과 막대 그래프

- src/main/kotlin/jimin/54week/문자열 게임 2.py
- src/main/kotlin/jimin/54week/우체국.py
- src/main/kotlin/jimin/54week/토마토.py
- src/main/kotlin/jimin/54week/항체 인식.py
```
항체 인식: ✅
토마토: ✅ 
문자열 게임: ✅ 
우체국: ⛔️
```
> [이지민] - 항체 인식, 토마토, 우체국, 문자열 게임 2

- src/main/kotlin/heejik/54week/꿀 따기.kt
- src/main/kotlin/heejik/54week/문자열 게임 2.kt
- src/main/kotlin/heejik/54week/스카이라인 쉬운거.kt
- src/main/kotlin/heejik/54week/우체국.kt
- src/main/kotlin/heejik/54week/토마토.kt
- src/main/kotlin/heejik/54week/항체 인식.kt
```
항체 인식: ✅
토마토: ✅
우체국: ⛔️
문자열 게임 2: ✅
```
- [꿀 따기](https://www.acmicpc.net/problem/21758)
- [스카이라인 쉬운거](https://www.acmicpc.net/problem/1863)
> [장희직] - 항체 인식, 토마토, 우체국, 문자열 게임 2

- src/main/kotlin/hyunsoo/54week/문자열 게임 2.kt
- src/main/kotlin/hyunsoo/54week/우체국.kt
- src/main/kotlin/hyunsoo/54week/토마토.kt
- src/main/kotlin/hyunsoo/54week/항체 인식.kt
```
항체 인식: ✅
토마토: ✅
우체국: ⛔️
문자열 게임 2: ⛔️
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---
> [전현수] - 항체 인식, 토마토, 우체국, 문자열 게임2

- src/main/kotlin/byeonghee/week54/DFS와 BFS.kt
- src/main/kotlin/byeonghee/week54/문자열 게임 2.kt
- src/main/kotlin/byeonghee/week54/스택 수열.kt
- src/main/kotlin/byeonghee/week54/우체국.kt
- src/main/kotlin/byeonghee/week54/토마토.kt
- src/main/kotlin/byeonghee/week54/항체 인식.kt
```
항체 인식: ✅
토마토: ✅
우체국: ⛔️
문자열 게임 2: ✅
```
- [스택 수열](https://www.acmicpc.net/problem/1874)
- [DFS와 BFS](https://www.acmicpc.net/problem/1260)
> [소병희] - 항체 인식, 토마토, 우체국, 문자열 게임 2

- src/main/kotlin/jimin/56week/나의 인생에는 수학과 함께.py
- src/main/kotlin/jimin/56week/루돌프의 반란.py
- src/main/kotlin/jimin/56week/이차원 배열과 연산.py
- src/main/kotlin/jimin/56week/톱니바퀴 (2).py
```
나의 인생에는 수학과 함께: ✅
톱니바퀴(2): ✅ 
이차원 배열과 연산: ✅
루돌프의 반란: ✅
```
> [이지민] - 나의 인생에는 수학과 함께, 톱니바퀴(2), 이차원 배열과 연산, 루돌프의 반란

- src/main/kotlin/heejik/57week/귤 고르기.py
- src/main/kotlin/heejik/57week/메이즈 러너.py
- src/main/kotlin/heejik/57week/아이템 줍기.py
- src/main/kotlin/heejik/57week/왕실의 기사 대결.py
```
왕실의 기사 대결: ✅
메이즈 러너: ✅
귤 고르기: ✅
아이템 줍기: ⛔️
```
> [장희직] - 왕실의 기사 대결, 메이즈 러너, 귤 고르기, 아이템 줍기

- src/main/kotlin/jimin/58week/술래잡기.py
- src/main/kotlin/jimin/58week/양치기 꿍.py
- src/main/kotlin/jimin/58week/포탑 부수기.py
```
술래잡기: ✅
양치기 꿍: ✅
포탑 부수기: ✅
```
> [이지민] - 술래잡기, 양치기 꿍, 포탑 부수기

- src/main/kotlin/byeonghee/BYEONGHEE_BJ_3187.java
- src/main/kotlin/byeonghee/week57/아이템 줍기.java
- src/main/kotlin/byeonghee/week58/BYEONGHEE_BJ_3187.java
- src/main/kotlin/byeonghee/week58/BYEONGHEE_CODETREE_DESTROY_THE_TURRET.java
- src/main/kotlin/byeonghee/week58/토끼와 경주.kt
```
양치기 꿍: ✅
포탑 부수기: ✅
토끼와 경주: ❎
```
> [소병희] - 양치기 꿍, 포탑 부수기, 토끼와 경주

- src/main/kotlin/heejik/58week/고대 문명 유적 탐사.py
- src/main/kotlin/heejik/58week/괄호의 값.kt
- src/main/kotlin/heejik/58week/꼬리잡기 놀이.py
- src/main/kotlin/heejik/58week/나무박멸.py
- src/main/kotlin/heejik/58week/달팽이 숫자.py
- src/main/kotlin/heejik/58week/드래곤 앤 던전.kt
- src/main/kotlin/heejik/58week/백만 장자 프로젝트.py
- src/main/kotlin/heejik/58week/술래잡.py
- src/main/kotlin/heejik/58week/싸움땅.py
- src/main/kotlin/heejik/58week/양치기 꿍.py
- src/main/kotlin/heejik/58week/예술성.py
- src/main/kotlin/heejik/58week/정육면체 한번 더 굴리기.py
- src/main/kotlin/heejik/58week/포탑 부수기.py
- src/main/kotlin/heejik/59week/동전.kt
- src/main/kotlin/heejik/59week/멀쩡한 사격형.kt
- src/main/kotlin/heejik/59week/호텔.kt
```
양치기 꿍: ✅
포탑 부수기: ✅
토끼와 경주: ⛔️
술래잡기: ✅
```
> [장희직] - 양치기 꿍, 포탑 부수기, 토끼와 경주, 술래잡기

- src/main/kotlin/byeonghee/week59/동전.kt
- src/main/kotlin/byeonghee/week59/멀쩡한 사각형.kt
- src/main/kotlin/byeonghee/week59/택배 배송.kt
- src/main/kotlin/byeonghee/week59/호텔.kt
```
동전, 택배 배송: ✅
호텔, 멀쩡한 사각형: ⛔️
```
> [소병희] - 동전, 호텔, 멀쩡한 사각형, 택배 배송

- src/main/kotlin/heejik/60week/공유기 설치.kt
- src/main/kotlin/heejik/60week/뮤탈리스크.kt
- src/main/kotlin/heejik/60week/스티커 재배치.kt
- src/main/kotlin/heejik/60week/트리의 지름.kt
```
트리의 지름: ⛔️
공유기 설치: ✅
뮤탈리스크:  ❎
```
- [스티커 재배치](https://www.acmicpc.net/problem/31092)
```
스티커 재배치: 👍
> [장희직] - 트리의 지름, 공유기 설치

- src/main/kotlin/jimin/60week/공유기 설치.kt
- src/main/kotlin/jimin/60week/뮤탈리스트.kt
- src/main/kotlin/jimin/60week/트리의 지름.kt
```
트리의 지름: ✅
뮤탈리스트: ⛔️
공유기 설치: ⛔️
```
> [이지민] - 공유기 설치, 트리의 지름, 뮤탈리스트

- src/main/kotlin/byeonghee/week60/공유기 설치.kt
- src/main/kotlin/byeonghee/week60/뮤탈리스크.kt
- src/main/kotlin/byeonghee/week60/트리의 지름.kt
```
트리의 지름: ✅
공유기 설치: ⛔️
뮤탈리스크: ⛔️
```
> [소병희] 공유기 설치, 트리의 지름, 뮤탈리스크

- src/main/kotlin/hyunsoo/61week/도넛 행성.kt
- src/main/kotlin/hyunsoo/61week/무인도 여행.kt
- src/main/kotlin/hyunsoo/61week/파일 합치기 3.kt
```
무인도 여행: ✅
파일 합치기 3: ✅
도넛 행성: ⛔️
하노이 탑: ❎
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---
> [전현수] - 무인도 여행, 파일 합치기 3, 도넛 행성

- src/main/kotlin/hyunsoo/58week/술래 잡기.kt
- src/main/kotlin/hyunsoo/58week/양치기 꿍.kt
- src/main/kotlin/hyunsoo/58week/토끼와 경주.kt
- src/main/kotlin/hyunsoo/58week/포탑 부수기.kt
```
양치기 꿍: ✅
술래 잡기: ✅
포탑 부수기: ❎
토끼와 경주: ❎
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---
> [전현수] - 양치기 꿍, 술래 잡기

- src/main/kotlin/hyunsoo/62week/Coins.kt
- src/main/kotlin/hyunsoo/62week/경쟁적 전염.kt
- src/main/kotlin/hyunsoo/62week/최소 스패닝 트리.kt
- src/main/kotlin/hyunsoo/62week/카드 섞기.kt
```
최소 스패닝 트리: ✅
경쟁적 전염: ✅
Coins: ⛔️
카드 섞기: ✅
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---
> [전현수] - 최소 스패닝 트리, 경쟁적 전염, Coins, 카드 섞기

- src/main/kotlin/byeonghee/week62/Coins.kt
- src/main/kotlin/byeonghee/week62/경쟁적 전염.kt
- src/main/kotlin/byeonghee/week62/최소 스패닝 트리.kt
- src/main/kotlin/byeonghee/week62/카드 섞기.kt
```
최소 스패닝 트리, 카드 섞기, 경쟁적 전염, Coins: ✅
```
> [소병희] - 최소 스패닝 트리, 카드 섞기, 경쟁적 전염, Coins

- src/main/kotlin/heejik/63week/괄호 제거.py
- src/main/kotlin/heejik/63week/도시 건설.py
- src/main/kotlin/heejik/63week/싸지방에 간 준하.py
- src/main/kotlin/heejik/63week/타일 채우기.py
```
괄호 제거: ✅
도시 건설: ✅
싸지방에 간 준하: ✅
타일 채우기: ⛔️
```
> [장희직] - 괄호 제거, 도시 건설, 싸지방에 간 준하, 타일 채우기

- src/main/kotlin/hyunsoo/63week/괄호 제거.kt
- src/main/kotlin/hyunsoo/63week/도시 건설.kt
- src/main/kotlin/hyunsoo/63week/싸지방에 간 준하.kt
- src/main/kotlin/hyunsoo/63week/타일 채우기.kt
```
도시 건설: ✅
괄호 제거: ✅
싸지방에 간 준하: ✅
타일 채우기: ⛔️
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---
> [전현수] - 도시 건설, 괄호 제거, 싸지방에 간 준하, 타일 채우기

- src/main/kotlin/heejik/64week/가장 긴 증가하는 부분 수열 4.kt
- src/main/kotlin/heejik/64week/내리막 길.py
- src/main/kotlin/heejik/64week/삼각 달팽이.py
- src/main/kotlin/heejik/64week/치즈.kt
```
가장 긴 증가하는 부분 수열 4: ✅
치즈: ✅
삼각 달팽이: ✅
내리막 길:⛔️ 
```
> [장희직] - 가장 긴 증가하는 부분 수열 4, 치즈, 삼각 달팽이, 내리막 길

- src/main/kotlin/hyunsoo/64week/가장 긴 증가하는 부분 수열 4.kt
- src/main/kotlin/hyunsoo/64week/내리막 길.kt
- src/main/kotlin/hyunsoo/64week/삼각 달팽이.kt
- src/main/kotlin/hyunsoo/64week/치즈.kt
```
치즈: ✅
가장 긴 증가하는 부분 수열 4 : ✅
내리막 길: ⛔️
삼각 달팽이 : ✅
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---
> [전현수] - 치즈, 가장 긴 증가하는 부분 수열 4, 내리막 길, 삼각 달팽이

- src/main/kotlin/byeonghee/week64/가장 긴 증가하는 부분 수열 4.kt
- src/main/kotlin/byeonghee/week64/내리막 길.kt
- src/main/kotlin/byeonghee/week64/삼각 달팽이.kt
- src/main/kotlin/byeonghee/week64/치즈.kt
```
치즈, 가장 긴 증가하는 부분 수열 4, 삼각 달팽이: ✅
내리막 길: ⛔️
```
> [소병희] - 내리막 길, 치즈, 가장 긴 증가하는 부분 수열 4, 삼각 달팽이

- src/main/kotlin/byeonghee/week65/사과나무.kt
- src/main/kotlin/byeonghee/week65/후위 표기식.kt
> [소병희] - 사과나무, 후위 표기식

- src/main/kotlin/jimin/65week/괄호 회전하기.py
- src/main/kotlin/jimin/65week/사과나무.py
> [이지민] - 사과나무, 괄호 회전하기

- src/main/kotlin/hyunsoo/65week/괄호 회전하기.kt
- src/main/kotlin/hyunsoo/65week/캐슬 디펜스.kt
- src/main/kotlin/hyunsoo/65week/후위 표기식.kt
```
괄호 회전하기: ✅
후위 표기식: ⛔️
캐슬 디펜스: ✅
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---
> [전현수] - 괄호 회전하기, 후위 표기식, 캐슬 디펜스

- src/main/kotlin/heejik/65week/괄호 회전하기.kt
- src/main/kotlin/heejik/65week/사과나무.kt
- src/main/kotlin/heejik/65week/캐슬 디펜스.kt
- src/main/kotlin/heejik/65week/후위 표기식.kt
```
괄호 회전하기: ✅, 
후위 표기식,: ⛔️ 
사과나무: ⛔️,
캐슬 디펜스: ✅
```
>  [장희직] - 괄호 회전하기, 후위 표기식, 사과나무, 캐슬 디펜스

- src/main/kotlin/jimin/66week/맥주 마시면서 걸어가기.py
- src/main/kotlin/jimin/66week/순회강연.py
- src/main/kotlin/jimin/66week/용액.py
- src/main/kotlin/jimin/66week/혼자서 하는 틱택토.py
```
순회강연: ✅
용액: ✅
맥주 마시면서 걸어가기: ⛔️
혼자서 하는 틱택토: ✅ 
```
> [이지민] - 순회강연, 용액, 맥주 마시면서 걸어가기, 혼자서 하는 틱택토

- src/main/kotlin/heejik/66week/맥주 마시면서 걸어가기.py
- src/main/kotlin/heejik/66week/순회강연.kt
- src/main/kotlin/heejik/66week/용액.kt
- src/main/kotlin/heejik/66week/혼자서 하는 틱택토.kt
```
용액: ✅
순회강연: ✅
혼자서 하는 틱택톡: ⛔️
맥주 마시면서 걸어다니기: ✅
> [장희직] - 용액, 순회강연, 혼자서 하는 틱택톡, 맥주 마시면서 걸어다니기
