wellFoundedDevelopers/Algorithm

src/main/kotlin/hyunsoo/2week/단어 뒤집기 2.kt
src/main/kotlin/hyunsoo/2week/숫자 정사각형.kt
src/main/kotlin/hyunsoo/2week/올바른 배열.kt
src/main/kotlin/hyunsoo/2week/지뢰 찾기.kt

```
숫자 정사각형: ✅
단어 뒤집기 2: ✅
지뢰 찾기: ✅
올바른 배열: ✅
숫자 야구: ❎
```
이번 주는 너무 바빠서 많은 문제를 풀지는 못했네요..
숫자야구 암만 해설을 봐도 이해가 안가요.....
---

[전현수] - 숫자 정사각형, 단어 뒤집기 2, 지뢰 찾기, 올바른 배열

---

src/main/kotlin/jimin/2week/단어 뒤집기2.kt
src/main/kotlin/jimin/2week/숫자 야구.kt
src/main/kotlin/jimin/2week/숫자 정사각형.kt
src/main/kotlin/jimin/2week/올바른 배열.kt
src/main/kotlin/jimin/2week/지뢰 찾기.kt

```
숫자 정사각형: ✅
단어 뒤집기 2: ✅
지뢰 찾기: ✅
올바른 배열: ✅
숫자 야구: ✅
```
- 문자를 길이로 자르기 : ` 문자열.chucked(숫자) `
- 시간초과 - 출력 빠르게 하기 : 
`""` 로 초기화하지 말고, `StringBuilder()`  사용하기.
이때 문자열 더하기는 `+=` 로 하지 않고 `append`를 사용한다.

[이지민] - 숫자 정사각형, 단어 뒤집기 2, 지뢰 찾기, 올바른 배열, 숫자 야구

---

src/main/kotlin/byeonghee/2week/NumberBaseball.kt
src/main/kotlin/byeonghee/2week/NumberSquare.kt
src/main/kotlin/byeonghee/2week/ReverseWord.kt
src/main/kotlin/byeonghee/2week/올바른배열.kt
src/main/kotlin/byeonghee/2week/지뢰찾기.kt

```
숫자 정사각형: ✅
숫자 야구: ✅
단어 뒤집기 2: ✅
올바른 배열: ⛔
지뢰 찾기: ⛔
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```

[소병희] - 숫자 정사각형

---

src/main/kotlin/hyunsoo/3week/단어 나누기.kt
src/main/kotlin/hyunsoo/3week/소셜 네트워크.kt
src/main/kotlin/hyunsoo/3week/주유소.kt
src/main/kotlin/hyunsoo/3week/할아버지는 유명해!.kt
src/main/kotlin/hyunsoo/3week/현수막.kt
src/main/kotlin/hyunsoo/3week/회전 초밥.kt

```
현수막: ✅
할아버지는 유명해!: ✅
단어 나누기: ✅
주유소: ⛔️ ( 58/100 )
소셜 네트워크: ✅
```
[회전초밥](https://www.acmicpc.net/problem/2531)
Kotlin에서 `List<String>`을 `List<Char>`로 형변환 시키고 싶다면, `List<String>.map { it.first() }` 와 같이 어차피 길이가 하나이므로 첫값에 접근하여 Char로 형변환이 가능
할이버지는 유명해! 문제에서 IntArray에서 최댓값을 구하려고 .max()를 사용했더니 컴파일 오류가 발생하네요...
그래서 그냥 내림차순으로 뒤집고 첫 번째 값으로 최댓값을 판별했습니다.
---

[전현수] - 현수막, 할아버지는 유명해!, 단어 나누기, 주유소, 소셜 네트워크

---

src/main/kotlin/byeonghee/2week/올바른배열.kt
src/main/kotlin/byeonghee/2week/올바른배열_2.kt
src/main/kotlin/byeonghee/2week/지뢰찾기.kt
src/main/kotlin/byeonghee/3week/단어나누기.kt
src/main/kotlin/byeonghee/3week/소셜네트워크.kt
src/main/kotlin/byeonghee/3week/주유소.kt
src/main/kotlin/byeonghee/3week/할아버지는유명해.kt
src/main/kotlin/byeonghee/3week/현수막.kt

```
주유소: ✅
할아버지는 유명해!: ✅
현수막: ✅
단어 나누기: ✅
소셜네트워크: ✅
```
- 코드에 사용하지는 않았지만 스코프함수를 통해 swap하는 법을 새로 알게 되었습니다.
```kotlin
a = b.also { b = a }
```
- 외울 함수
- `.none {}` ↔️ `.any{}`
- 조건 확인(?)

[소병희] - 현수막, 주유소, 할아버지는 유명해!, 단어 나누기, 소셜네트워크

---

src/main/kotlin/heejik/3week/단어 나누기.kt
src/main/kotlin/heejik/3week/소셜네트워크.kt
src/main/kotlin/heejik/3week/주유소.kt
src/main/kotlin/heejik/3week/할아버지는 유명해!.kt
src/main/kotlin/heejik/3week/현수막.kt

```
현수막: ✅
주유소: ✅
할아버지는 유명해!: ✅
단어 나누기: ✅
소셜네트워크: ✅
```
추천: 👍  
비추천: 👎  
---
- 종료 체크를 예쁘게(?) 했습니다.👍
```kotlin
val (n, m) = readln().trim().split(' ').map { it.toInt() }
.also { if (it.contains(0)) exitProcess(0) }
```
- map 에 a(key) 값이 존재하지않다면 b만 들어있는 set으로 초기화하구 존재한다면 b 를 추가해주도록 했습니다.
```kotlin
friend[a] = friend[a]?.apply { add(b) } ?: mutableSetOf(b)
```

[장희직] - 현수막, 주유소, 할아버지는 유명해!, 단어 나누기, 소셜네트워크

---

src/main/kotlin/byeonghee/4week/NBA 농구.kt
src/main/kotlin/byeonghee/4week/그림.kt
src/main/kotlin/byeonghee/4week/놀라운 문자열.kt
src/main/kotlin/byeonghee/4week/보물.kt
src/main/kotlin/byeonghee/4week/외판원 순회 2.kt

```
보물: ✅
그림: ✅
외판원 순회 2: ✅
놀라운 문자열: ✅
NBA 농구: ✅
```
- [외판원 순회 반례](https://www.acmicpc.net/board/view/26647)

[소병희] 보물, 그림, 놀라운 문자열, NBA 농구, 외판원 순회 2

---

src/main/kotlin/jimin/3week/소셜 네트워크.kt
src/main/kotlin/jimin/3week/할아버지는 유명해!.kt
src/main/kotlin/jimin/3week/현수막.kt
src/main/kotlin/jimin/4week/NBA 농구.kt
src/main/kotlin/jimin/4week/그림.kt
src/main/kotlin/jimin/4week/놀라운 문자열.kt
src/main/kotlin/jimin/4week/보물.kt
src/main/kotlin/jimin/4week/외판원 순회2.kt

```
그림: ✅
보물: ✅
놀라운 문자열: ✅
NBA 농구: ✅
외판원 순회2: ✅
```
`문자열.padStart(length, padChar)`를 하면 원하는 문자를 채워서 해당 길이에 맞는 문자열을 만들 수 있다.

[이지민] 그림, 보물, 놀라운 문자열, NBA 농구, 외판원 순회2

---

src/main/kotlin/heejik/4week/NBA 농구.kt
src/main/kotlin/heejik/4week/그림.kt
src/main/kotlin/heejik/4week/놀라운 문자열.kt
src/main/kotlin/heejik/4week/보물.kt
src/main/kotlin/heejik/4week/외판원 순회2.kt

```
그림: ✅
보물: ✅
놀라운 문자열: ✅
NBA 농구: ✅
외판원 순회2: ✅
```
- 재귀는 너무 어렵다..
- `forEachIndexed` 가 많이 유용하다. python 의 enumerate 를 항상 깜빡해서 사용하지 못 한 경험이 떠오른다..

[장희직] 그림, 보물, 놀라운 문자열, NBA 농구, 외판원 순회2

---

src/main/kotlin/hyunsoo/5week/가로수.kt
src/main/kotlin/hyunsoo/5week/랜선 자르기.kt
src/main/kotlin/hyunsoo/5week/바닥 장식.kt
src/main/kotlin/hyunsoo/5week/빙고.kt
src/main/kotlin/hyunsoo/5week/크로스워드.kt
src/main/kotlin/hyunsoo/5week/킹.kt

```
킹: ✅
바닥 장식: ✅
빙고: ✅
랜선 자르기: ✅
가로수: ⛔️
```
- [크로스워드](https://www.acmicpc.net/problem/1706)
가로수....가 저는 어려웠습니다,,,
---

[전현수] 킹, 바닥 장식, 빙고, 랜선 자르기, 가로수 

---

src/main/kotlin/byeonghee/3week/단어나누기.kt
src/main/kotlin/byeonghee/3week/소셜네트워크.kt
src/main/kotlin/byeonghee/3week/주유소.kt
src/main/kotlin/byeonghee/3week/할아버지는유명해.kt
src/main/kotlin/byeonghee/3week/현수막.kt
src/main/kotlin/byeonghee/5week/가로수.kt
src/main/kotlin/byeonghee/5week/랜선 자르기.kt
src/main/kotlin/byeonghee/5week/바닥장식.kt
src/main/kotlin/byeonghee/5week/빙고.kt
src/main/kotlin/byeonghee/5week/킹.kt
src/main/kotlin/byeonghee/template.kt

```
킹: ✅
바닥 장식: ✅
빙고: ✅
랜선 자르기: ✅
가로수: ✅
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
- 리스트를 가공하여 맵으로 바꾸는 방법
```kotlin
val map = list.map { it.makeKey() to it.makeVal() }.toMap()
```
- gcd
```kotlin
fun gcd(a: Int, b: Int) = if (b == 0) return a else gcd(b, a % b)
```
- 특정 값이 아닌 첫 정답(?)의 인덱스를 찾는 이진 탐색
```kotlin
fun bisearch(n: Int, lb: Int, ub: Int): Int {
// lb: inclusive, ub: exclusive
while(lb + 1 < ub) {
mid = lb + ((ub - lb) / 2)  // int 범위를 초과하지 않고 중간값 계산
if(list[mid] >= n) lb = mid //mid가 정답 범위 내 인덱스일 때
else ub = mid
}
return lb
}
```

[소병희] 킹, 바닥 장식, 빙고, 랜선 자르기, 가로수

---

src/main/kotlin/jimin/4week/외판원 순회2.kt
src/main/kotlin/jimin/5week/랜선 자르기.kt
src/main/kotlin/jimin/6week/근손실.kt
src/main/kotlin/jimin/6week/비슷한 단어.kt
src/main/kotlin/jimin/6week/아기 상어2.kt
src/main/kotlin/jimin/6week/트리의 부모 찾기.kt
src/main/kotlin/jimin/6week/회의실 배정.kt

```
근손실: ✅
비슷한 단어: ✅
아기상어2: ✅
트리의 부모 찾기: ✅
회의실 배정: ✅
```
리스트 미리 초기화하기 : `MutableList(숫자) { i -> 원하는 값 }`
최댓값의 index 구하기 : `val maxIdx = 리스트.indices.maxBy { 리스트[it] } ?: -1`
---

[이지민] 근손실, 비슷한 단어, 아기상어2, 트리의 부모 찾기, 회의실 배정

---

src/main/kotlin/hyunsoo/6week/근손실.kt
src/main/kotlin/hyunsoo/6week/비슷한 단어.kt
src/main/kotlin/hyunsoo/6week/아기 상어 2.kt
src/main/kotlin/hyunsoo/6week/톱니바퀴.kt
src/main/kotlin/hyunsoo/6week/트리의 부모 찾기.kt
src/main/kotlin/hyunsoo/6week/회의실 배정.kt

```
근손실: ✅
트리의 부모 찾기: ✅
비슷한 단어: ✅
회의실 배정: ✅
아기상어 2: ✅
```
- [톱니바퀴](https://www.acmicpc.net/problem/14891) <- 이 친구 재밌습니다!!
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
- 확장함수로 빼는 것들이 확실히 뭔가 이쁜데...! 성능적으로 이점이 있는지 잘 모르겠네요
- 아기상어 문제... 
- 문제를 잘못읽어서 삽질
- dfs로 접근해서 삽질
- 방문처리 안해서 삽질
- 병희님이 operator를 데이터 클래스 내부로 변경하신 것을 보고 반영..!!
---

[전현수] 근손실, 트리의 부모 찾기, 비슷한 단어, 회의실 배정, 아기상어 2

---

src/main/kotlin/heejik/4week/외판원 순회2.kt
src/main/kotlin/heejik/5week/랜선 자르기.kt
src/main/kotlin/heejik/5week/빙고.kt
src/main/kotlin/heejik/6week/근손실.kt
src/main/kotlin/heejik/6week/비슷한 단어.kt
src/main/kotlin/heejik/6week/아기상어.kt
src/main/kotlin/heejik/6week/트리의 부모 찾기.kt
src/main/kotlin/heejik/6week/회의실 배정.kt

```
근손실: ⛔️
비슷한 단어: ✅
아기상어2: ⛔️
트리의 부모 찾기:  ✅
회의실 배정: ✅
```
재귀와 bfs, dfs 공부가 더 필요하다.

[장희직] 근손실, 비슷한 단어, 아기상어2, 트리의 부모 찾기, 회의실 배정

---

src/main/kotlin/jimin/6week/아기 상어2.kt
src/main/kotlin/jimin/6week/트리의 부모 찾기.kt
src/main/kotlin/jimin/6week/회의실 배정.kt
src/main/kotlin/jimin/7week/미로 만들기.kt
src/main/kotlin/jimin/7week/차이를 최대로.kt
src/main/kotlin/jimin/7week/최소 힙.kt
src/main/kotlin/jimin/7week/한 줄로 서기.kt
src/main/kotlin/jimin/7week/흙길 보수하기.kt

```
최소 힙: ✅
차이를 최대로: ✅
흙길 보수하기: ✅
한 줄로 서기: ✅
미로 만들기: ✅
```
미로 만들기에서 런타임 에러 (ArrayIndexOutOfBounds)가 뜨는데 해결하지 못했다..
---

[이지민] 최소 힙, 차이를 최대로, 흙길 보수하기, 한 줄로 서기, 미로 만들기

---

src/main/kotlin/hyunsoo/7week/미로 만들기.kt
src/main/kotlin/hyunsoo/7week/지름길.kt
src/main/kotlin/hyunsoo/7week/차이를 최대로.kt
src/main/kotlin/hyunsoo/7week/최소 힙.kt
src/main/kotlin/hyunsoo/7week/한 줄로 서기.kt
src/main/kotlin/hyunsoo/7week/흙길 보수하기.kt

```
최소 힙: ✅
차이를 최대로: ✅
흙길 보수하기: ✅
한 줄로 서기: ✅
미로 만들기: ✅
```
- [지름길](https://www.acmicpc.net/problem/1446)
---

[전현수] 최소 힙, 차이를 최대로, 흙길 보수하기, 한 줄로 서기, 미로 만들기

---

src/main/kotlin/hyunsoo/8week/단축키 지정.kt
src/main/kotlin/hyunsoo/8week/문자열 집합.kt
src/main/kotlin/hyunsoo/8week/색종이 만들기.kt
src/main/kotlin/hyunsoo/8week/쇠막대기.kt
src/main/kotlin/hyunsoo/8week/창고 다각형.kt

```
문자열 집합: ✅
색종이 만들기: ✅
창고 다각형: ✅
쇠막대기: ✅
단축키 지정: ✅
```
- 정신없는 일주일을 보내서... 겨우 다 풀었네요ㅜㅜ
---

[전현수] 문자열 집합, 색종이 만들기, 창고 다각형, 쇠막대기, 단축키 지정

---

src/main/kotlin/jimin/8week/단축키 지정.kt
src/main/kotlin/jimin/8week/문자열 집합.kt
src/main/kotlin/jimin/8week/색종이 만들기.kt
src/main/kotlin/jimin/8week/쇠막대기.kt
src/main/kotlin/jimin/8week/창고 다각형.kt

```
문자열 집합: ✅
색종이 만들기: ✅
창고 다각형: ✅
쇠막대기: ✅
단축키 지정: ✅
```
---

[이지민] 문자열 집합, 색종이 만들기, 창고 다각형, 쇠막대기, 단축키 지정

---

src/main/kotlin/heejik/8week/단축키 지정.kt
src/main/kotlin/heejik/8week/문자열 집합.kt
src/main/kotlin/heejik/8week/색종이 만들기.kt
src/main/kotlin/heejik/8week/쇠막대기.kt
src/main/kotlin/heejik/8week/창고 다각형.kt

```
문자열 집합: ✅
색종이 만들기: ✅
창고 다각형: ✅
쇠막대기: ✅
단축키 지정: ✅
```
```kotlin 
wordsList.forEach { words ->
val wordList = words.split(' ')
var answer = ""
var isApplied = false
wordList.forEach wordList@ { word ->
if (isApplied) {
answer += "$word "
return@wordList
}
```
forEach 가 반복되면 뒤에 ~~@ 를 추가해 지정가능!!

[장희직] 문자열 집합, 색종이 만들기, 창고 다각형, 쇠막대기, 단축키 지정

---

src/main/kotlin/byeonghee/8week/단축키 지정.kt
src/main/kotlin/byeonghee/8week/문자열 집합.kt
src/main/kotlin/byeonghee/8week/색종이 만들기.kt
src/main/kotlin/byeonghee/8week/쇠막대기.kt
src/main/kotlin/byeonghee/8week/창고 다각형.kt

```
창고 다각형: ✅
색종이 만들기: ✅
단축키 지정: ✅
쇠막대기: ✅
문자열 집합: ✅
```

[소병희] 창고 다각형, 색종이 만들기, 단축키 지정, 쇠막대기, 문자열 집합

---

.idea/inspectionProfiles/Project_Default.xml
src/main/kotlin/hyunsoo/9week/1, 2, 3 더하기 4.kt
src/main/kotlin/hyunsoo/9week/Java vs C++.kt
src/main/kotlin/hyunsoo/9week/도어맨.kt
src/main/kotlin/hyunsoo/9week/배열 복원하기.kt
src/main/kotlin/hyunsoo/9week/후위 표기식2.kt

```
Java vs C++: ✅
배열 복원하기: ✅
도어맨: ✅
1, 2, 3 더하기 4: ⛔️
후위 표기식 2: ❎
```
- 그룹 프로젝트 갱장히 바쁘네요..
- 후위 표기식2는 자꾸 인덱스 에러가 나는데 이유를 모르겠습니다..
---

[전현수] Java vs C++, 배열 복원하기, 도어맨, 1, 2, 3 더하기 4, 후위 표기식 2

---

src/main/kotlin/jimin/9week/1, 2, 3 더하기 4.kt
src/main/kotlin/jimin/9week/Java vs C++.kt
src/main/kotlin/jimin/9week/도어맨.kt
src/main/kotlin/jimin/9week/배열 복원하기.kt
src/main/kotlin/jimin/9week/후위 표기식2.kt

```
Java vs C++: ✅
1,2,3 더하기 4: ✅
도어맨: ✅
배열 복원하기: ✅
후위 표기식2: ✅
```

[이지민] Java vs C++, 1,2,3 더하기 4, 도어맨, 배열 복원하기, 후위 표기식2

---

src/main/kotlin/hyunsoo/10week/달팽이.kt
src/main/kotlin/hyunsoo/10week/병든 나이트.kt
src/main/kotlin/hyunsoo/10week/숫자 게임.kt
src/main/kotlin/hyunsoo/10week/햄버거 분배.kt

```
숫자 게임: ✅
달팽이: ✅
햄버거 분배: ✅
병든 나이트: ⛔️
```
- 그리디가 진짜 감이 잘 안잡히네요

[전현수] 숫자 게임, 달팽이, 햄버거 분배, 병든 나이트

---

src/main/kotlin/byeonghee/10week/달팽이.kt
src/main/kotlin/byeonghee/10week/병든 나이트.kt
src/main/kotlin/byeonghee/10week/숫자 게임.kt
src/main/kotlin/byeonghee/10week/햄버거 분배.kt

```
숫자 게임: ✅
달팽이: ✅
햄버거 분배: ✅
병든 나이트: ✅
```

[소병희] 숫자 게임, 달팽이, 햄버거 분배, 병든 나이트

---

src/main/kotlin/jimin/10week/달팽이.kt
src/main/kotlin/jimin/10week/병든 나이트.kt
src/main/kotlin/jimin/10week/숫자 게임.kt
src/main/kotlin/jimin/10week/햄버거 분배.kt

```
달팽이: ✅
병든 나이트: ✅
숫자 게임: ✅
햄버거 분해: ⛔ 
```
```
```

[이지민] 달팽이, 병든 나이트, 숫자 게임, 햄버거 분해

---

src/main/kotlin/heejik/10week/달팽이.kt
src/main/kotlin/heejik/10week/병든 나이트.kt
src/main/kotlin/heejik/10week/숫자 게임.kt
src/main/kotlin/heejik/10week/햄버거 분배.kt
src/main/kotlin/heejik/9week/후위 표기식2.kt

```
숫자 게임: ✅
달팽이: ✅
햄버거 분배: ✅
병든 나이트: ✅
```
달팽이 문제에서 많이 헤맸습니다..

[장희직] 숫자 게임, 달팽이, 햄버거 분배, 병든 나이트

---

src/main/kotlin/byeonghee/11week/꽃길.kt
src/main/kotlin/byeonghee/11week/예산.kt
src/main/kotlin/byeonghee/11week/왕복.kt
src/main/kotlin/byeonghee/11week/팰린드롬 만들기.kt

```
꽃길: ✅
팰린드롬 만들기: ✅
예산: ✅
왕복: ✅
```

[소병희] 꽃길, 팰린드롬 만들기, 예산, 왕복

---

src/main/kotlin/jimin/11week/꽃길.kt
src/main/kotlin/jimin/11week/예산.kt
src/main/kotlin/jimin/11week/왕복.kt
src/main/kotlin/jimin/11week/팰린드롬 만들기.kt

```
팰린드롬 만들기: ✅
예산: ✅
왕복: ✅
꽃길 : ✅
```
---

[이지민] 팰린드롬 만들기, 예산, 왕복, 꽃길

---

src/main/kotlin/hyunsoo/11week/꽃길.kt
src/main/kotlin/hyunsoo/11week/예산.kt
src/main/kotlin/hyunsoo/11week/왕복.kt
src/main/kotlin/hyunsoo/11week/팰린드롬 만들기.kt

```
팰린드롬 만들기: ✅
예산: ✅
왕복: ✅
꽃길: ✅
```
- 어렵다...
- 오랜만에 DFS를 풀어서 그런지.. 2차원이라서 갑자기 헷갈린건지... 어려웠습니다,,,
---

[전현수] 팰린드롬 만들기, 예산, 왕복, 꽃길

---

src/main/kotlin/heejik/10week/달팽이.kt
src/main/kotlin/heejik/10week/숫자 게임.kt
src/main/kotlin/heejik/11week/꽃길.kt
src/main/kotlin/heejik/11week/예산.kt
src/main/kotlin/heejik/11week/왕복.kt
src/main/kotlin/heejik/11week/팰린드롬 만들기.kt

```
팰린드롬 만들기: ✅
예산: ✅
왕복: ✅
꽃길 : ✅
```
꽃길 문제 다른 분들은 어떻게 푸셨는 지 궁금합니다

[장희직] 팰린드롬 만들기, 예산, 왕복, 꽃길 

---

src/main/kotlin/byeonghee/12week/그룹 단어 체커.kt
src/main/kotlin/byeonghee/12week/수리공 항승.kt
src/main/kotlin/byeonghee/12week/안녕.kt

```
그룹 단어 체커: ✅
수리공 항승: ✅
안녕: ⛔️
트럭: ❌
```

[소병희] 그룹 단어 체커, 수리공 항승, 안녕

---

src/main/kotlin/byeonghee/13week/DNA.kt
src/main/kotlin/byeonghee/13week/기적의 매매법.kt
src/main/kotlin/byeonghee/13week/등수 구하기.kt
src/main/kotlin/byeonghee/13week/수 이어 쓰기 1.kt

```
기적의 매매법: ✅
DNA: ✅
등수 구하기: ✅
수 이어 쓰기 1: ✅
```

[소병희] 기적의 매매법, DNA, 등수 구하기, 수 이어 쓰기 1

---

src/main/kotlin/hyunsoo/17week/링크와 스타트.kt
src/main/kotlin/hyunsoo/17week/수 고르기.kt
src/main/kotlin/hyunsoo/17week/스택.kt
src/main/kotlin/hyunsoo/17week/이진 검색 트리.kt
src/main/kotlin/hyunsoo/17week/좌표 압축.kt
src/main/kotlin/hyunsoo/17week/추월.kt
src/main/kotlin/hyunsoo/17week/트리 순회.kt

```
수 고르기: ✅
추월: ✅
트리 순회: ✅
링크와 스타트: ✅
```
- [좌표 압축](https://www.acmicpc.net/problem/18870)
- [스택](https://www.acmicpc.net/problem/10828)
코틀린 하다가 C++ 살짝해보니까 죽을 것 같아요...
---

[전현수] 수 고르기, 추월, 트리 순회, 링크와 스타트

---

src/main/kotlin/byeonghee/17week/링크와 스타트.kt
src/main/kotlin/byeonghee/17week/수 고르기.kt
src/main/kotlin/byeonghee/17week/추월.kt
src/main/kotlin/byeonghee/17week/트리 순회.kt

```
추월: ✅
수 고르기: ✅
트리 순회: ✅
링크와 스타트: ✅
```

[소병희] 추월, 수 고르기, 트리 순회, 링크와 스타트

---

src/main/kotlin/heejik/13week/등수 구하기.kt
src/main/kotlin/heejik/13week/🐜 기적의 매매법 🐜.kt
src/main/kotlin/heejik/14week/대표 자연수.kt
src/main/kotlin/heejik/14week/링크와 스타트.kt
src/main/kotlin/heejik/14week/별 찍기 - 19.kt
src/main/kotlin/heejik/14week/수 고르기.kt
src/main/kotlin/heejik/14week/추월.kt
src/main/kotlin/heejik/14week/트리 순회.kt

```
추월: ✅
수 고르기: ✅
트리 순회: ⛔️
링크와 스타트: ⛔️
```
- [별 찍기 - 19](https://www.acmicpc.net/problem/10994) 
- [대표 자연수](https://www.acmicpc.net/problem/2548)

[장희직] 추월, 수 고르기, 트리 순회, 링크와 스타트

---

src/main/kotlin/byeonghee/18week/Z.kt
src/main/kotlin/byeonghee/18week/거짓말.kt
src/main/kotlin/byeonghee/18week/레이저빔은 어디로.kt
src/main/kotlin/byeonghee/18week/부분수열의 합.kt

```
Z: ✅
부분수열의 합: ✅
거짓말: ✅
레이저빔은 어디로: ✅
```

[소병희] Z, 부분수열의 합, 거짓말, 레이저빔은 어디로

---

src/main/kotlin/hyunsoo/18week/Z.kt
src/main/kotlin/hyunsoo/18week/거짓말.kt
src/main/kotlin/hyunsoo/18week/레이저빔은 어디로.kt
src/main/kotlin/hyunsoo/18week/부분수열의 합.kt

```
거짓말: ✅
부분수열의 합: ✅
레이저빔은 어디로: ✅
Z: ✅
```
[서로소 집합](https://soopeach.tistory.com/73)

[전현수] - 거짓말, 부분수열의 합, 레이저빔은 어디로, Z

---

src/main/kotlin/heejik/13week/DNA.kt
src/main/kotlin/hyunsoo/13week/DNA.kt
src/main/kotlin/jimin/17week/수 고르기.kt
src/main/kotlin/jimin/18week/Z.kt
src/main/kotlin/jimin/18week/거짓말.kt
src/main/kotlin/jimin/18week/동전 0.kt
src/main/kotlin/jimin/18week/레이저빔은 어디로.kt
src/main/kotlin/jimin/18week/부분수열의 합.kt

```
Z: ✅
거짓말: ✅
레이저빔은 어디로: ✅
부분수열의 합: ✅
```
- [동전 0](https://www.acmicpc.net/problem/11047)
새롭게 pull을 하다가,, 희직님과 현수님의 max()가 제 것에서 안돌아가서 maxOrNull로 바꿔놓았습니다...! 죄송합니다 🙏 
---

[이지민] Z, 거짓말, 레이저빔은 어디로, 부분수열의 합

---

src/main/kotlin/byeonghee/19week/2xn 타일링.kt
src/main/kotlin/byeonghee/19week/단지번호붙이기.kt
src/main/kotlin/byeonghee/19week/동전1.kt
src/main/kotlin/byeonghee/19week/숨바꼭질.kt

```
단지번호붙이기: ✅
동전 1: ✅
2xn 타일링: ✅
숨바꼭질: ✅
```

[소병희] 단지번호붙이기, 동전 1, 2xn 타일링, 숨바꼭질

---

src/main/kotlin/hyunsoo/19week/2xn 타일링.kt
src/main/kotlin/hyunsoo/19week/단지번호붙이기.kt
src/main/kotlin/hyunsoo/19week/동전 1.kt
src/main/kotlin/hyunsoo/19week/숨바꼭질.kt
src/main/kotlin/hyunsoo/19week/적록색약.kt
src/main/kotlin/hyunsoo/19week/통계학.kt
src/main/kotlin/hyunsoo/19week/평범한 배낭.kt
src/main/kotlin/hyunsoo/19week/피보나치 함수.kt
src/main/kotlin/hyunsoo/template.kt

```
단지번호붙이기: ✅
동전 1: ⛔️
2xn 타일링: ⛔️
숨바꼭질: ⛔️
```
- [통계학](https://www.acmicpc.net/problem/2108)
- [평범한 배낭](https://www.acmicpc.net/problem/12865)
- [적록색약](https://www.acmicpc.net/problem/10026)
- [피보나치 함수](https://www.acmicpc.net/problem/1003)
```
평범한 배낭: 👍  
- 냅색의 표본...
```
- DP, BFS는 어렵네요...
---

[전현수] - 단지번호붙이기, 2xn 타일링, 동전 1, 숨바꼭질

---

src/main/kotlin/heejik/19week/2×n 타일링.kt
src/main/kotlin/heejik/19week/단지번호붙이기.kt
src/main/kotlin/heejik/19week/동전 1.kt
src/main/kotlin/heejik/19week/숨바꼭질.kt
src/main/kotlin/heejik/19week/치킨 배달.kt
src/main/kotlin/heejik/19week/홀수 홀릭 호석.kt

```
단지번호붙이기: ✅
동전 1: ⛔️
2xn 타일링: ✅
숨바꼭질: ✅
```
- [홀수 홀릭 호석](https://www.acmicpc.net/problem/20164) 👍
- [치킨배달](https://www.acmicpc.net/problem/15686) 👍
---

[장희직] - 단지번호붙이기, 2xn 타일링, 동전 1, 숨바꼭질

---

src/main/kotlin/jimin/19week/날짜 계산.kt
src/main/kotlin/jimin/19week/리모컨.kt
src/main/kotlin/jimin/20week/별자리 만들기.kt
src/main/kotlin/jimin/20week/안전 영역.kt
src/main/kotlin/jimin/20week/양.kt
src/main/kotlin/jimin/20week/에너지 모으기.kt

```
양 : ✅
별자리 만들기 : ⛔️
안전구역 : ✅ 
에너지 모으기: ✅ 
```
새로운 유형 조아요

[이지민] - 양, 별자리 만들기, 안전구역, 에너지 모으기

---

src/main/kotlin/hyunsoo/20week/별자리_만들기.kt
src/main/kotlin/hyunsoo/20week/안전 영역.kt
src/main/kotlin/hyunsoo/20week/양.kt
src/main/kotlin/hyunsoo/20week/에너지 모으기.kt
src/main/kotlin/hyunsoo/20week/최소 스패닝 트리.kt
src/main/kotlin/hyunsoo/20week/최소비용_구하기.kt
src/main/kotlin/hyunsoo/20week/택배 배송.kt

```
양: ✅
별자리 만들기: ✅
안전구역: ✅
에너지 모으기: ✅
```
- [최소 스패닝 트리](https://www.acmicpc.net/problem/1197) 👍 
- MST 구현 연습용으로 굿
- [택배 배송](https://www.acmicpc.net/problem/5972) 👍 
- 다익스트라 구현 연습용으로 굿
- [최소비용 구하기](https://www.acmicpc.net/problem/1916) 👍 
- 다익스트라 구현 연습용으로 굿
- 병희님이 MST 문제를 가져와주신 덕분에 크루스칼 알고리즘을 복습할 수 있었습니다~ 감사합니다(__)
- [크루스칼 알고리즘](https://us05web.zoom.us/j/85853862023?pwd=QzF3OWJQMkNJNFQ4bzJzeUVPNUttZz09)

[전현수] - 양, 별자리 만들기, 안전구역, 에너지 모으기

---

src/main/kotlin/heejik/20week/별자리 만들기.kt
src/main/kotlin/heejik/20week/안전 영역.kt
src/main/kotlin/heejik/20week/양.kt
src/main/kotlin/heejik/20week/에너지 모으기.kt

```
양 : ✅
별자리 만들기 : ✅
안전구역 : ✅ 
에너지 모으기: ✅ 
```
`별자리 만들기를 잼게 풀었습니다.`

[장희직] - 양, 별자리 만들기, 안전구역, 에너지 모으기

---

src/main/kotlin/hyunsoo/21week/별 찍기 - 13.kt
src/main/kotlin/hyunsoo/21week/부등호.kt
src/main/kotlin/hyunsoo/21week/스위치 켜고 끄기.kt
src/main/kotlin/hyunsoo/21week/스티커.kt
src/main/kotlin/hyunsoo/21week/알파벳.kt

```
스위치 켜고 끄기: ✅
알파벳: ✅
부등호: ✅
스티커: ⛔️
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---

[전현수] - 스위치 켜고 끄기, 알파벳, 부등호, 스티커

---

src/main/kotlin/heejik/21week/부등호.kt
src/main/kotlin/heejik/21week/스위치 켜고 끄기.kt
src/main/kotlin/heejik/21week/스티커.kt
src/main/kotlin/heejik/21week/알파벳.kt

```
스위치 켜고 끄기: ✅
알파벳: ✅
부등호: ✅
스티커: ⛔️
```

[장희직] - 스위치 켜고 끄기, 알파벳, 부등호, 스티커

---

src/main/kotlin/jimin/21week/부등호.kt
src/main/kotlin/jimin/21week/스위치 켜고 끄기.kt
src/main/kotlin/jimin/21week/스티커.kt
src/main/kotlin/jimin/21week/알파벳.kt

```
스위치 켜고 끄기: ✅
알파벳: ✅
부등호: ✅
스티커: ⛔️
```

[이지민] - 스위치 켜고 끄기, 알파벳, 부등호, 스티커

---

src/main/kotlin/byeonghee/21week/부등호.kt
src/main/kotlin/byeonghee/21week/스위치 켜고 끄기.kt
src/main/kotlin/byeonghee/21week/스티커.kt
src/main/kotlin/byeonghee/21week/알파벳.kt
src/main/kotlin/byeonghee/21week/톱니바퀴.kt

```
알파벳: ✅
부등호: ✅
스위치 켜고 끄기: ✅
스티커: ✅
```

[소병희] 알파벳, 부등호, 스위치 켜고 끄기, 스티커

---

src/main/kotlin/jimin/22week/ABCDE.kt
src/main/kotlin/jimin/22week/감시 피하기.kt
src/main/kotlin/jimin/22week/최소 회의실 개수.kt
src/main/kotlin/jimin/22week/평범한 배낭.kt

```
최소 회의실 개수: ⛔️
ABCDE : ✅
평범한 배낭 : ⛔️
감시 피하기: ❎
```

[이지민] 최소 회의실 개수, ABCDE, 평범한 배낭

---

src/main/kotlin/hyunsoo/22week/ABCDE.kt
src/main/kotlin/hyunsoo/22week/감시 피하기.kt
src/main/kotlin/hyunsoo/22week/최소 회의실 개수.kt
src/main/kotlin/hyunsoo/22week/평범한 배낭.kt

```
감시 피하기: ✅
ABCDE: ✅
평범한 배낭: ⛔️
최소 회의실 개수: ❎
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---

[전현수] - 감시 피하기, ABCDE, 평범한 배낭, 최소 회의실 개수

---

src/main/kotlin/byeonghee/22week/ABCDE.kt
src/main/kotlin/byeonghee/22week/감시 피하기.kt
src/main/kotlin/byeonghee/22week/최소 회의실 개수.kt
src/main/kotlin/byeonghee/22week/평범한 배낭.kt

```
최소 회의실 개수: ✅
ABCDE: ✅
평범한 배낭: ⛔️
감시 피하기: ⛔️
```

[소병희] 최소 회의실 개수, ABCDE, 평범한 배낭, 감시 피하기

---

src/main/kotlin/heejik/21week/스위치 켜고 끄기.kt
src/main/kotlin/heejik/21week/알파벳.kt
src/main/kotlin/heejik/22week/ABCDE.kt
src/main/kotlin/heejik/22week/감시 피하기.kt
src/main/kotlin/heejik/22week/여왕벌.kt
src/main/kotlin/heejik/22week/죽음의 게임.kt
src/main/kotlin/heejik/22week/최소 회의실 개수.kt
src/main/kotlin/heejik/22week/탑.kt
src/main/kotlin/heejik/22week/평범한 배낭.kt

```
최소 회의실 개수: ✅
ABCDE: ✅
평범한 배낭: ✅
감시 피하기: ✅
```
- [여왕벌](https://www.acmicpc.net/problem/10836): 👍
- [탑](https://www.acmicpc.net/problem/2493): 👍
- [죽음의 게임](https://www.acmicpc.net/problem/17204): 👉
```

[장희직] 최소 회의실 개수, ABCDE, 평범한 배낭, 감시 피하기

---

src/main/kotlin/byeonghee/23week/로봇 청소기.kt
src/main/kotlin/byeonghee/23week/보물섬.kt
src/main/kotlin/byeonghee/23week/센서.kt
src/main/kotlin/byeonghee/23week/합분해.kt

```
센서: ✅
로봇 청소기: ✅
합분해: ✅
보물섬: ✅
```

[소병희] 센서, 로봇 청소기, 합분해, 보물섬

---

src/main/kotlin/heejik/23week/로봇 청소기.kt
src/main/kotlin/heejik/23week/보물섬.kt
src/main/kotlin/heejik/23week/센서.kt
src/main/kotlin/heejik/23week/합분해.kt

```
로봇 청소기: ✅
보물섬: ✅
센서: ✅
합분해: ✅
```

[장희직] - 로봇 청소기, 보물섬, 센서, 합분해 

---

src/main/kotlin/hyunsoo/24week/도서관.kt
src/main/kotlin/hyunsoo/24week/좋은 수열.kt
src/main/kotlin/hyunsoo/24week/트리와 쿼리.kt

```
트리와 쿼리: ✅
도서관: ✅
좋은 수열: ⛔️
행렬 테두리 회전하기: ❎
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
제 맥북 좀 살려주세요..
---

[전현수] - 트리와 쿼리, 도서관, 좋은 수열

---

src/main/kotlin/heejik/24week/도서관.kt
src/main/kotlin/heejik/24week/좋은수열.kt
src/main/kotlin/heejik/24week/트리와 쿼리.kt
src/main/kotlin/heejik/24week/행렬 테두리 회전하기.kt

```
도서관: ✅
좋은수열: ⛔️
쿼리와 트리: ✅
행렬 테두리 회전하기: ✅
```

[장희직] 도서관, 좋은수열, 쿼리와 트리, 행렬 테두리 회전하기

---

src/main/kotlin/jimin/24week/도서관.kt
src/main/kotlin/jimin/24week/좋은수열.kt
src/main/kotlin/jimin/24week/트리와 쿼리.kt
src/main/kotlin/jimin/24week/행렬 테두리 회전하기.kt

```
도서관: ✅
좋은수열: ⛔ 
쿼리와 트리: ⛔️
행렬 테두리 회전하기: ✅ 
```
```
```

[이지민] 도서관, 좋은수열, 쿼리와 트리, 행렬 테두리 회전하기

---

src/main/kotlin/byeonghee/24week/도서관.kt
src/main/kotlin/byeonghee/24week/좋은수열.kt
src/main/kotlin/byeonghee/24week/트리와 쿼리.kt
src/main/kotlin/byeonghee/24week/행렬 테두리 회전하기.kt

```
트리와 쿼리: ✅
행렬 테두리 회전하기: ⛔
도서관: ✅
좋은수열: ✅
```

[소병희] 트리와 쿼리, 행렬 테두리 회전하기, 도서관, 좋은수열

---

src/main/kotlin/heejik/25week/감시.kt
src/main/kotlin/heejik/25week/선수과목.kt
src/main/kotlin/heejik/25week/오큰수.kt
src/main/kotlin/heejik/25week/톱니바퀴.kt

```
감시: ✅
선수과목: ⛔️
오큰수: ✅
톱니바퀴: ✅
```

[장희직] 감시, 선수과목, 오큰수, 톱니바퀴

---

src/main/kotlin/jimin/25week/감시.kt
src/main/kotlin/jimin/25week/선수과목.kt
src/main/kotlin/jimin/25week/오큰수.kt
src/main/kotlin/jimin/25week/톱니바퀴.kt

```
감시: ✅
톱니바퀴: ✅ 
선수과목: ✅ 
오큰수: ⛔️
```

[이지민] 감시, 톱니바퀴, 오큰수, 선수과목

---

src/main/kotlin/hyunsoo/25week/감시.kt
src/main/kotlin/hyunsoo/25week/선수과목.kt
src/main/kotlin/hyunsoo/25week/오큰수.kt
src/main/kotlin/hyunsoo/25week/톱니바퀴.kt

```
선수과목: ✅
오큰수: ⛔️
감시: ✅
톱니바퀴: ✅
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
- 감시의 코드 상태가...ㅎㅎ
---

[전현수] 선수과목, 오큰수, 감시, 톱니바퀴

---

src/main/kotlin/byeonghee/25week/감시.kt
src/main/kotlin/byeonghee/25week/선수과목.kt
src/main/kotlin/byeonghee/25week/오큰수.kt
src/main/kotlin/byeonghee/25week/톱니바퀴.kt

``` 
감시: ✅
오큰수: ✅
톱니바퀴: ✅
선수과목: ✅
```

[소병희] 감시, 오큰수, 톱니바퀴, 선수과목

---

src/main/kotlin/hyunsoo/26week/절댓값 힙 쉽게.kt
src/main/kotlin/hyunsoo/26week/절댓값 힙.kt
src/main/kotlin/hyunsoo/26week/치즈.kt
src/main/kotlin/hyunsoo/26week/치킨 배달.kt
src/main/kotlin/hyunsoo/26week/표현 가능한 이진트리.kt

```
절댓값 힙: ✅
치킨 배달: ✅
치즈: ✅
표현 가능한 이진트리: ⛔️
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---

[전현수] - 절댓값 힙, 치킨 배달, 치즈, 표현 가능한 이진트리

---

src/main/kotlin/jimin/26week/절댓값 힙.kt
src/main/kotlin/jimin/26week/치즈.kt
src/main/kotlin/jimin/26week/치킨 배달.kt

```
치킨 배달: ✅
절댓값 힙: ✅
치즈: ✅
표현가능한 이진트리: ❎ 
```
다 풀었다고 착각하여 한 문제를 못풀었습니다,,
---

[이지민] 치킨 배달, 절댓값 힙, 치즈

---

src/main/kotlin/byeonghee/week27/문자열 폭발.kt
src/main/kotlin/byeonghee/week27/주사위 굴리기.kt
src/main/kotlin/byeonghee/week27/친구 네트워크.kt
src/main/kotlin/byeonghee/week27/팰린드롬.kt

```
친구 네트워크: ✅
주사위 굴리기: ✅
문자열 폭발: ✅
팰린드롬?: ✅
```

[소병희] 친구 네트워크, 주사위 굴리기, 문자열 폭발, 팰린드롬?

---

src/main/kotlin/heejik/27week/문자열 폭발.kt
src/main/kotlin/heejik/27week/주사위 굴리기.kt
src/main/kotlin/heejik/27week/친구 네트워크.kt
src/main/kotlin/heejik/27week/팰린드롬.kt

```
친구 네트워크: ⛔️
주사위 굴리기: ✅
문자열 폭발: ✅
팰린드롬?: ✅
```
`점점 시간초과가 많이 뜨네요 ㅠ`

[장희직] 친구 네트워크, 주사위 굴리기, 문자열 폭발, 팰린드롬?

---

src/main/kotlin/jimin/28week/드래곤 커브.kt
src/main/kotlin/jimin/28week/미세먼지 안녕!.kt
src/main/kotlin/jimin/28week/연구소.kt
src/main/kotlin/jimin/28week/친구비.kt

```
드래곤 커브: ⛔ 
미세먼지 안녕!: ✅
연구소: ✅ 
친구비: ✅ 
```
```
추천: 👍  
비추천: 👎  
```

[이지민] - 드래곤 커브, 미세먼지 안녕!, 연구소, 친구비

---

src/main/kotlin/heejik/28week/드래곤 커브.kt
src/main/kotlin/heejik/28week/미세먼지 안녕!.kt
src/main/kotlin/heejik/28week/연구소.kt
src/main/kotlin/heejik/28week/친구비.kt

```
연구소: ✅
친구비: ✅
드래곤 커브: ✅
미세먼지 안녕!: ✅
```

[장희직] - 연구소, 친구비, 드래곤 커브, 미세먼지 안녕!

---

src/main/kotlin/heejik/29week/빙산.kt
src/main/kotlin/heejik/29week/상어 초등학교.kt
src/main/kotlin/heejik/29week/안녕.kt
src/main/kotlin/heejik/29week/컨베이어 벨트 위의 로봇.kt

```
안녕: ✅
컨베이어 벨트 위의 로봇: ✅
빙산: ✅
상어 초등학교 : ✅
```

[장희직] 안녕, 컨베이어 벨트 위의 로봇, 빙산, 상어 초등학교 

---

src/main/kotlin/jimin/28week/연구소.kt
src/main/kotlin/jimin/28week/친구비.kt
src/main/kotlin/jimin/29week/빙산.kt
src/main/kotlin/jimin/29week/상어 초등학교.kt
src/main/kotlin/jimin/29week/안녕.kt
src/main/kotlin/jimin/29week/컨베이어 벨트 위의 로봇.kt

```
안녕: ✅
컨베이어 벨트 위의 로봇: ✅
빙산: ✅
상어 초등학교: ✅
```

[이지민] 안녕, 컨베이어 벨트 위의 로봇, 빙산, 상어 초등학교

---

src/main/kotlin/byeonghee/week29/빙산.kt
src/main/kotlin/byeonghee/week29/상어 초등학교.kt
src/main/kotlin/byeonghee/week29/안녕.kt
src/main/kotlin/byeonghee/week29/컨베이어벨트위의로봇.kt

```
컨베이어 벨트 위의 로봇: ✅
빙산: ✅
상어초등학교: ✅
안녕: ✅
```

[소병희] 컨베이어 벨트 위의 로봇, 빙산, 상어초등학교, 안녕

---

src/main/kotlin/hyunsoo/29week/빙산.kt
src/main/kotlin/hyunsoo/29week/상어 초등학교.kt
src/main/kotlin/hyunsoo/29week/안녕.kt
src/main/kotlin/hyunsoo/29week/컨베이어 벨트 위의 로봇.kt

```
빙산: ✅
컨베이어 벨트 위의 로봇: ⛔️
안녕: ✅
상어 초등학교: ✅
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---

[전현수] - 빙산, 컨베이어 벨트 위의 로봇, 안녕, 상어 초등학교

---

src/main/kotlin/hyunsoo/30week/경로 찾기.kt
src/main/kotlin/hyunsoo/30week/과제.kt
src/main/kotlin/hyunsoo/30week/마법사 상어와 비바라기.kt
src/main/kotlin/hyunsoo/30week/테트로미노.kt

```
경로 찾기: ✅
마법사 상어와 비바라기: ✅
과제: ✅
테트로미노: ⛔️
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---

[전현수] - 경로 찾기, 마법사 상어와 비바라기, 과제, 테트로미노

---

src/main/kotlin/byeonghee/week30/경로 찾기.kt
src/main/kotlin/byeonghee/week30/과제.kt
src/main/kotlin/byeonghee/week30/마법사상어와비바라기.kt
src/main/kotlin/byeonghee/week30/테트로미노.kt

```
경로 찾기: ✅
테트로미노: ✅
마법사 상어와 비바라기: ✅
과제: ✅
```

[소병희] 경로 찾기, 테트로미노, 마법사 상어와 비바라기, 과제

---

src/main/kotlin/heejik/30week/경로 찾기.kt
src/main/kotlin/heejik/30week/과제.kt
src/main/kotlin/heejik/30week/마법사 상어와 비바라기.kt
src/main/kotlin/heejik/30week/테트로미노.kt

```
경로 찾기: ✅
마법사 상어와 비바라기: ✅
과제: ✅
테트로미노: ✅
```

[장희직] - 경로 찾기, 마법사 상어와 비바라기, 과제, 테트로미노

---

src/main/kotlin/hyunsoo/33week/물병.kt
src/main/kotlin/hyunsoo/33week/운동.kt
src/main/kotlin/hyunsoo/33week/이모티콘.kt
src/main/kotlin/hyunsoo/33week/집합.kt

```
집합: ✅
운동: ✅
이모티콘: ⛔️
이모티콘: ⛔️
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
`감을 다 잃었어요...`
---

[전현수] - 집합, 운동, 이모티콘, 물병

---

src/main/kotlin/heejik/30week/과제.kt
src/main/kotlin/heejik/31week/램프.kt
src/main/kotlin/heejik/31week/물병.kt
src/main/kotlin/heejik/31week/물통.kt
src/main/kotlin/heejik/31week/빗물.kt
src/main/kotlin/heejik/31week/사과나무.kt
src/main/kotlin/heejik/31week/숫자고르기.kt
src/main/kotlin/heejik/31week/신입 사원.kt
src/main/kotlin/heejik/31week/암호 만들기.kt
src/main/kotlin/heejik/31week/운동.kt
src/main/kotlin/heejik/31week/이모티콘.kt
src/main/kotlin/heejik/31week/인구이동.kt
src/main/kotlin/heejik/31week/전깃줄.kt
src/main/kotlin/heejik/31week/집합.kt
src/main/kotlin/heejik/31week/토마토.kt
src/main/kotlin/heejik/31week/파이프 옮기기 1.kt
src/main/kotlin/heejik/31week/포도주 시식.kt
src/main/kotlin/jimin/27week/팰린드롬.kt

```
운동: ✅
물병: ⛔️
이모티콘: ✅
집합: ✅
```
- [램프](https://www.acmicpc.net/problem/1034)
- [물통](https://www.acmicpc.net/problem/2251)
- [빗물](https://www.acmicpc.net/problem/14719)
- [사과나무](https://www.acmicpc.net/problem/19539)
- [숫자고르기](https://www.acmicpc.net/problem/2668)
- [신입 사원](https://www.acmicpc.net/problem/1946)
- [암호 만들기](https://www.acmicpc.net/problem/1759)
- [인구이동](https://www.acmicpc.net/problem/16234)
- [전깃줄](https://www.acmicpc.net/problem/2565)
- [토마토](https://www.acmicpc.net/problem/7576)
- [파이프 옮기기 1](https://www.acmicpc.net/problem/17070)
- [포도주 시식](https://www.acmicpc.net/problem/2156)
```

[장희직] - 운동, 물병, 이모티콘, 집합

---

src/main/kotlin/jimin/30week/과제.py
src/main/kotlin/jimin/31week/물병.kt
src/main/kotlin/jimin/31week/운동.kt
src/main/kotlin/jimin/31week/이모티콘.kt
src/main/kotlin/jimin/31week/집합.kt

```
집합: ✅
이모티콘: ⛔️
물병: ⛔️
운동: ⛔️
```

[이지민] - 집합, 이모티콘, 물병, 운동

---

src/main/kotlin/byeonghee/week33/물병.kt
src/main/kotlin/byeonghee/week33/운동.kt
src/main/kotlin/byeonghee/week33/이모티콘.kt
src/main/kotlin/byeonghee/week33/집합.kt

```
운동: ⛔️
물병: ✅
이모티콘: ✅
집합: ✅
```

[소병희] 운동, 집합, 이모티콘, 물병

---

src/main/kotlin/jimin/34week/Contact.kt
src/main/kotlin/jimin/34week/연속된 부분 수열의 합.kt
src/main/kotlin/jimin/34week/저울.kt
src/main/kotlin/jimin/34week/행복 유치원.kt

```
저울: ✅
연속된 부분 수열의 합: ✅
Contact: ✅
행복 유치원: ✅
```
---

[이지민] - 저울, 연속된 부분 수열의 합, Contact, 행복 유치원

---

src/main/kotlin/byeonghee/week34/Contact.kt
src/main/kotlin/byeonghee/week34/연속된 부분 수열의 합.kt
src/main/kotlin/byeonghee/week34/저울.kt
src/main/kotlin/byeonghee/week34/행복 유치원.kt

```
Contact: ✅
행복 유치원: ✅
연속된 부분 수열의 합: ✅
저울: ✅
```

[소병희] Contact, 행복 유치원, 연속된 부분 수열의 합, 저울

---

src/main/kotlin/hyunsoo/34week/Contact.kt
src/main/kotlin/hyunsoo/34week/연속된 부분 수열의 합.kt
src/main/kotlin/hyunsoo/34week/저울.kt
src/main/kotlin/hyunsoo/34week/행복 유치원.kt

```
연속된 부분 수열의 합: ✅
행복 유치원: ⛔️
저울: ⛔️
Contact: ✅
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---

[전현수] - 연속된 부분 수열의 합, 행복 유치원, 저울, Contact

---

src/main/kotlin/heejik/34week/Contact.kt
src/main/kotlin/heejik/34week/연속된 부분 수열의 합.kt
src/main/kotlin/heejik/34week/저울.kt
src/main/kotlin/heejik/34week/행복 유치원.kt

```
연속된 부분 수열의 합: ✅
Contact: ✅
행복 유치원: ⛔️
저울: ⛔️
```

[장희직] - 연속된 부분 수열의 합, Contact, 행복 유치원, 저울

---

src/main/kotlin/jimin/35week/인구 이동.kt
src/main/kotlin/jimin/35week/카드 정렬하기.kt
src/main/kotlin/jimin/35week/토마토.kt

```
토마토: ✅
인구이동: ✅
카드 정렬하기: ✅
rgb거리 2: ❎
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```

[이지민] - 토마토, 인구 이동, 카드 정렬하기

---

src/main/kotlin/hyunsoo/38week/RGB거리 2.kt
src/main/kotlin/hyunsoo/38week/인구 이동.kt
src/main/kotlin/hyunsoo/38week/카드 정렬하기.kt
src/main/kotlin/hyunsoo/38week/토마토.kt

```
인구 이동: ✅
카드 정렬하기: ⛔️
토마토: ✅
RGB거리 2: ⛔️
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---

[전현수] - 인구 이동, 카드 정렬하기, 토마토, RGB거리 2 

---

src/main/kotlin/heejik/34week/연속된 부분 수열의 합.kt
src/main/kotlin/heejik/35week/Puyo Puyo.kt
src/main/kotlin/heejik/35week/RGB거리 2.kt
src/main/kotlin/heejik/35week/가장 큰 정사각형.kt
src/main/kotlin/heejik/35week/단어 수학.kt
src/main/kotlin/heejik/35week/인구 이동.kt
src/main/kotlin/heejik/35week/장군.kt
src/main/kotlin/heejik/35week/카드 정렬하기.kt
src/main/kotlin/heejik/35week/토마토.kt

```
인구 이동: ✅
RGB거리 2: ⛔️
토마토: ✅
카드 정렬하기: ⛔️
```
- [Puyo Puyo](https://www.acmicpc.net/problem/11559): 👍
- [가장 큰 정사각형](https://www.acmicpc.net/problem/1915) : 👍
- [장군](https://www.acmicpc.net/problem/16509): 👉
- [단어 수학](https://www.acmicpc.net/problem/1339): 👍

[장희직] - 인구 이동, RGB거리 2, 토마토, 카드 정렬하기

---

src/main/kotlin/hyunsoo/39week/봄버맨.kt
src/main/kotlin/hyunsoo/39week/오목.kt
src/main/kotlin/hyunsoo/39week/자유 이용권.kt
src/main/kotlin/hyunsoo/39week/줄세우기.kt

```
오목: ✅
봄버맨: ✅
자유 이용권: ⛔️
줄세우기: ⛔️
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---

[전현수] - 오목, 봄버맨, 자유 이용권, 줄세우기

---

src/main/kotlin/heejik/36week/봄버맨.kt
src/main/kotlin/heejik/36week/오목.kt
src/main/kotlin/heejik/36week/자유 이용권.kt
src/main/kotlin/heejik/36week/줄세우기.kt

```
오목: ✅
봄버맨: ✅
자유 이용권: ⛔️
줄세우기: ⛔️
```

[장희직] - 오목, 봄버맨, 자유 이용권, 줄세우기

---

src/main/kotlin/byeonghee/week39/봄버맨.kt
src/main/kotlin/byeonghee/week39/오목.kt
src/main/kotlin/byeonghee/week39/자유이용권.kt
src/main/kotlin/byeonghee/week39/줄세우기.kt

```
오목: ✅
줄세우기: ⛔️
봄버맨: ✅
자유이용권: ✅
```

[소병희] 오목, 줄세우기, 봄버맨, 자유이용권

---

.idea/misc.xml
src/main/kotlin/hyunsoo/39week/줄세우기.kt
src/main/kotlin/hyunsoo/41week/개미의 이동.kt
src/main/kotlin/hyunsoo/41week/로봇 시뮬레이션.kt
src/main/kotlin/hyunsoo/41week/지름길.kt
src/main/kotlin/hyunsoo/41week/트리.kt

```
지름길: ✅
로봇 시뮬레이션: ✅
개미의 이동: ⛔️
트리: ❎
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---

[전현수] - 지름길, 로봇 시뮬레이션, 개미의 이동, 트리

---

src/main/kotlin/jimin/36week/봄버맨.kt
src/main/kotlin/jimin/36week/오목.kt
src/main/kotlin/jimin/36week/자유 이용권.kt
src/main/kotlin/jimin/41week/개미의 이동.kt
src/main/kotlin/jimin/41week/로봇 시뮬레이션.kt
src/main/kotlin/jimin/41week/지름길.kt
src/main/kotlin/jimin/41week/트리.kt

```
지름길: ✅
개미의 이동: ⛔️
트리: ✅
로봇 시뮬레이션: ❎
```

[이지민] 지름길, 개미의 이동, 트리, 로봇 시뮬레이션

---

src/main/kotlin/heejik/40week/개미의 이동.kt
src/main/kotlin/heejik/40week/로봇 시뮬레이션.kt
src/main/kotlin/heejik/40week/지름길.kt
src/main/kotlin/heejik/40week/트리.kt

```
지름길: ✅
개미의 이동: ⛔️
트리: ✅
로봇 시뮬레이션: ✅
```

[장희직] 지름길, 개미의 이동, 트리, 로봇 시뮬레이션 

---

src/main/kotlin/byeonghee/week41/개미의 이동.kt
src/main/kotlin/byeonghee/week41/로봇 시뮬레이션.kt
src/main/kotlin/byeonghee/week41/지름길.kt
src/main/kotlin/byeonghee/week41/트리.kt

```
트리: ✅
로봇 시뮬레이션: ✅
개미의 이동: ⛔️
지름길: ⛔️
```

[소병희] 트리, 지름길, 개미의 이동, 로봇 시뮬레이션

---

src/main/kotlin/hyunsoo/42week/1, 2, 3 더하기 3.kt
src/main/kotlin/hyunsoo/42week/30.kt
src/main/kotlin/hyunsoo/42week/로또.kt
src/main/kotlin/hyunsoo/42week/바이러스.kt
src/main/kotlin/hyunsoo/42week/블로그.kt
src/main/kotlin/hyunsoo/42week/연속합.kt
src/main/kotlin/hyunsoo/42week/이동하기.kt

```
로또: ✅
이동하기: ✅
바이러스: ✅
블로그: ✅
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
`다행히 아예 초기화가 되지는 않았나봐요ㅜㅜ`
---

[전현수] - 로또, 이동하기, 바이러스, 블로그

---

src/main/kotlin/heejik/41week/개미의 이동.kt
src/main/kotlin/heejik/41week/로봇 시뮬레이션.kt
src/main/kotlin/heejik/41week/지름길.kt
src/main/kotlin/heejik/41week/트리.kt
src/main/kotlin/heejik/42week/로또.kt
src/main/kotlin/heejik/42week/바이러스.kt
src/main/kotlin/heejik/42week/블로그.kt
src/main/kotlin/heejik/42week/이동하기.kt

```
로또: ✅
바이러스: ✅
이동하기: ✅
블로그: ✅

[장희직] 로또, 바이러스, 이동하기, 블로그

---

src/main/kotlin/jimin/42week/로또.kt
src/main/kotlin/jimin/42week/바이러스.kt
src/main/kotlin/jimin/42week/블로그.kt
src/main/kotlin/jimin/42week/이동하기.kt

```
로또: ⛔️
바이러스: ✅
블로그: ✅ 
이동하기: ✅ 
```

[이지민] 로또, 바이러스, 블로그, 이동하기

---

src/main/kotlin/jimin/45week/게임.py
src/main/kotlin/jimin/45week/디스크 컨트롤러.py
src/main/kotlin/jimin/45week/연산자 끼워넣기.py

```
연산자 끼워넣기: ✅
게임: ⛔️
디스크 컨트롤러: ✅ 
```

[이지민] - 연산자 끼워넣기, 게임, 디스크 컨트롤러

---

src/main/kotlin/hyunsoo/45week/A와 B.kt
src/main/kotlin/hyunsoo/45week/게임.kt
src/main/kotlin/hyunsoo/45week/디스크 컨트롤러.kt
src/main/kotlin/hyunsoo/45week/연산자 끼워넣기.kt

```
A와 B: ✅
게임: ✅
디스크 컨트롤러: ⛔️
연산자 끼워넣기: ❎
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---

[전현수] - A와 B, 게임, 디스크 컨트롤러

---

src/main/kotlin/byeonghee/week45/A와 B.kt
src/main/kotlin/byeonghee/week45/게임.kt
src/main/kotlin/byeonghee/week45/연산자 끼워넣기.kt

```
게임: ✅
연산자 끼워넣기: ✅
A와 B: ✅
디스크 컨트롤러: ❎
```

[소병희] 게임, 연산자 끼워넣기, A와 B

---

src/main/kotlin/jimin/46week/경주로 건설.py
src/main/kotlin/jimin/46week/농장 관리.py
src/main/kotlin/jimin/46week/빌런 호석.py
src/main/kotlin/jimin/46week/숨박꼭질 3.py

```
빌런 호석: ✅
농장 관리: ⛔️
경주로 건설: ⛔️
숨박꼭질 3: ⛔️
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```

[이지민] - 농장 관리, 빌런 호석, 숨박꼭질 3, 경주로 건설

---

src/main/kotlin/hyunsoo/46week/농장 관리.kt
src/main/kotlin/hyunsoo/46week/빌런 호석.kt
src/main/kotlin/hyunsoo/46week/숨바꼭질3.kt

```
숨바꼭질3: ✅
농장 관리: ✅
빌런 호석: ⛔️
경주로 건설: ❎
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---

[전현수] - 숨바꼭질3, 농장 관리, 빌런 호석

---

src/main/kotlin/heejik/46week/농장 관리.kt
src/main/kotlin/heejik/46week/빌런 호석.kt
src/main/kotlin/heejik/46week/숨바꼭질 3.kt
src/main/kotlin/heejik/46week/숨바꼭질.kt

```
숨바꼭질 3: ❎
농장 관리: ✅
빌런 호석: ⛔️
```
명절 잘 보내세유~

[장희직] - 숨바꼭질 3, 농장 관리, 빌런 호석

---

src/main/kotlin/jimin/49week/노드사이의 거리.py
src/main/kotlin/jimin/49week/벼락치기.py
src/main/kotlin/jimin/49week/빗물.py
src/main/kotlin/jimin/49week/할인 행사.py

```
노드사이의 거리: ✅
벼락치기: ⛔️
빗물: ⛔️
할인 행사: ✅ 
```

[이지민] - 노드사이의 거리, 벼락차기, 빗물, 할인 행사

---

src/main/kotlin/byeonghee/week49/노드사이의 거리.kt
src/main/kotlin/byeonghee/week49/벼락치기.kt
src/main/kotlin/byeonghee/week49/빗물.kt
src/main/kotlin/byeonghee/week49/할인 행사.kt
src/main/kotlin/byeonghee/week50/두 큐 합 같게 만들기.kt
src/main/kotlin/byeonghee/week50/북쪽나라의 도로.kt
src/main/kotlin/byeonghee/week50/숫자고르기.kt
src/main/kotlin/byeonghee/week50/연구소2.kt

```
숫자고르기: ✅
북쪽나라의 도로: ✅
두 큐 합 같게 만들기: ✅
연구소2: ❎
```

[소병희] - 숫자고르기, 북쪽나라의 도로, 두 큐 합 같게 만들기

---

src/main/kotlin/hyunsoo/52week/222-풀링.kt
src/main/kotlin/hyunsoo/52week/N번째 큰 수.kt
src/main/kotlin/hyunsoo/52week/종이의 개수.kt
src/main/kotlin/hyunsoo/52week/택배 배달과 수거하기.kt

```
N번째 큰 수: ✅
종이의 개수: ✅
222-폴링: ✅
택배 배달과 수거하기: ❎
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---

[전현수] - N번째 큰 수, 종이의 개수, 222-폴링

---

src/main/kotlin/hyunsoo/55week/꿀 따기.kt
src/main/kotlin/hyunsoo/55week/보이저 1호.kt
src/main/kotlin/hyunsoo/55week/세탁소 사장 동혁.kt
src/main/kotlin/hyunsoo/55week/여행 가자.kt
src/main/kotlin/hyunsoo/55week/짐 챙기는 숌.kt
src/main/kotlin/hyunsoo/55week/컵홀더.kt
src/main/kotlin/hyunsoo/55week/피로도.kt

```
보이저 1호: ✅
여행 가자: ✅
꿀 따기: ⛔️
피로도: ✅
```
- [세탁소 사장 동혁](https://www.acmicpc.net/problem/2720)
- [컵홀더](https://www.acmicpc.net/problem/2810)
- [짐 챙기는 숌](https://www.acmicpc.net/problem/1817)
```
추천: 👍  
비추천: 👎  
그리디 기초를 풀어보았습니다..
```
---

[전현수] - 보이저 1호, 여행 가자, 꿀 따기, 피로도, 세탁소 사장 동혁, 컵홀더 , 짐 챙기는 숌

---

src/main/kotlin/jimin/55week/꿀 따기.py
src/main/kotlin/jimin/55week/보이저 1호.py
src/main/kotlin/jimin/55week/여행 가자.py
src/main/kotlin/jimin/55week/피로도.py

```
여행 가자: ✅
꿀 따기: ⛔️
피로도: ✅
보이저 1호: ✅ 
```

[이지민] - 꿀 따기, 여행 가자, 피로도, 보이저 1호

---

src/main/kotlin/heejik/54week/꿀 따기.kt
src/main/kotlin/heejik/54week/항체 인식.kt
src/main/kotlin/heejik/55week/N으로 표현.kt
src/main/kotlin/heejik/55week/가장 먼 노드.kt
src/main/kotlin/heejik/55week/단어 변환.kt
src/main/kotlin/heejik/55week/베스트 앨범.kt
src/main/kotlin/heejik/55week/보이저 1호.kt
src/main/kotlin/heejik/55week/사다리 조작.kt
src/main/kotlin/heejik/55week/섬 연결하기.kt
src/main/kotlin/heejik/55week/여행 가자.kt
src/main/kotlin/heejik/55week/여행 경로.kt
src/main/kotlin/heejik/55week/전력망을 둘로 나누기.kt
src/main/kotlin/heejik/55week/최단경로.kt
src/main/kotlin/heejik/55week/피로도.kt

```
꿀 따기: ✅
여행 가자: ✅
피로도: ✅
보이저 1호: ✅
```
- [문제](링크)
- [문제](링크)

[장희직] - 꿀 따기, 여행 가자, 피로도, 보이저 1호

---

src/main/kotlin/byeonghee/week55/꿀 따기.kt
src/main/kotlin/byeonghee/week55/보이저 1호.kt
src/main/kotlin/byeonghee/week55/여행 가자.kt
src/main/kotlin/byeonghee/week55/피로도.kt

```
보이저 1호: ✅
여행 가자: ✅
꿀 따기: ⛔️
피로도: ⛔️
```

[소병희] - 보이저 1호, 여행 가자, 꿀 따기, 피로도

---

src/main/kotlin/heejik/55week/최단경로.kt
src/main/kotlin/heejik/56week/나의 인생에는 수학과 함께.kt
src/main/kotlin/heejik/56week/루돌프의 반란.py
src/main/kotlin/heejik/56week/이차원 배열과 연산.py
src/main/kotlin/heejik/56week/톱니바퀴(2).py

```
나의 인생에는 수학과 함께: ✅
루돌프의 반란: ✅
톱니바퀴 (2): ✅
이차원 배열과 연산: ✅

[장희직] - 나의 인생에는 수학과 함께, 루돌프의 반란, 톱니바퀴 (2), 이차원 배열과 연산

---

src/main/kotlin/byeonghee/week56/나의 인생에는 수학과 함께.kt
src/main/kotlin/byeonghee/week56/루돌프의 반란.kt
src/main/kotlin/byeonghee/week56/이차원 배열과 연산.kt
src/main/kotlin/byeonghee/week56/톱니바퀴2.kt

```
나의 인생에는 수학과 함께: ✅
이차원 배열과 연산: ✅
루돌프의 반란:  ❎
톱니바퀴2: ❎
```

[소병희] 나의 인생에는 수학과 함께, 이차원 배열과 연산

---

src/main/kotlin/hyunsoo/57week/귤 고르기.kt
src/main/kotlin/hyunsoo/57week/왕실의 기사 대결.kt

```
왕실의 기사 대결: ✅
귤 고르기: ✅
메이즈 러너: ❎
아이템 줍기: ❎
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---

[전현수] - 왕실의 기사 대결, 귤 고르기

---

src/main/kotlin/byeonghee/week57/귤 고르기.kt
src/main/kotlin/byeonghee/week57/아이템 줍기.java

```
귤 고르기: ✅
나머지: ❎
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---
<br>
<br>
ex)
```
마인크래프트: ✅
숫자 야구: ✅
떡 먹는 호랑이: ⛔️
아기 상어 2: ✅
연구소 2: ❎
```
- [AC](https://www.acmicpc.net/problem/5430) - 골드라고 겁먹지 말자  
- [아기 상어](https://www.acmicpc.net/problem/16236) 👍 - 유명한 삼성 기출문제
- 이번 주는 과제가 너무 많아서 부득이하게 연구소 2를 풀지 못하였다.
```
(0 .. 100).fold(0){ total, next =>
total + next
}
```
fold를 위와 같이 사용하면 0 ~ 100까지의 모든 리스트의 값을 더해서 반환해준다.
- 문제가 너무 많아요

[소병희] - 귤 고르기

---

src/main/kotlin/jimin/57week/귤고르기.py
src/main/kotlin/jimin/57week/메이즈 러너.py
src/main/kotlin/jimin/57week/왕실의 기사 대결.py

```
왕실의 기사 대결: ✅
메이즈 러너: ✅ 
귤 고르기: ✅ 
아이템 줍기: ❎
```

[이지민] - 왕실의 기사 대결, 메이즈 러너, 귤 고르기

---

src/main/kotlin/heejik/58week/고대 문명 유적 탐사.py
src/main/kotlin/heejik/58week/괄호의 값.kt
src/main/kotlin/heejik/58week/꼬리잡기 놀이.py
src/main/kotlin/heejik/58week/나무박멸.py
src/main/kotlin/heejik/58week/달팽이 숫자.py
src/main/kotlin/heejik/58week/드래곤 앤 던전.kt
src/main/kotlin/heejik/58week/백만 장자 프로젝트.py
src/main/kotlin/heejik/58week/술래잡.py
src/main/kotlin/heejik/58week/싸움땅.py
src/main/kotlin/heejik/58week/양치기 꿍.py
src/main/kotlin/heejik/58week/예술성.py
src/main/kotlin/heejik/58week/정육면체 한번 더 굴리기.py
src/main/kotlin/heejik/58week/포탑 부수기.py
src/main/kotlin/heejik/59week/동전.kt
src/main/kotlin/heejik/59week/멀쩡한 사격형.kt
src/main/kotlin/heejik/59week/호텔.kt

```
동전: ⛔️
멀쩡한 사각형: ⛔️
호텔: ✅
```

[장희직] - 동전, 멀쩡한 사각형, 호텔

---

src/main/kotlin/jimin/58week/술래잡기.py
src/main/kotlin/jimin/58week/양치기 꿍.py
src/main/kotlin/jimin/58week/포탑 부수기.py
src/main/kotlin/jimin/59week/동전.py
src/main/kotlin/jimin/59week/멀쩡한 사각형.py
src/main/kotlin/jimin/59week/택배 배송.py
src/main/kotlin/jimin/59week/호텔.py

```
택배 배송: ✅
멀쩡한 사각형: ✅
호텔: ✅
동전: ✅
```

[이지민] - 택배 배송, 멀쩡한 사각형, 호텔, 동전

---

src/main/kotlin/byeonghee/week61/도넛 행성.kt
src/main/kotlin/byeonghee/week61/무인도 여행.kt
src/main/kotlin/byeonghee/week61/파일 합치기.kt
src/main/kotlin/byeonghee/week61/하노이 탑.kt

```
무인도 여행, 파일 합치기, 도넛 행성: ✅
하노이 탑: ⛔️
```

[소병희] 무인도 여행, 파일 합치기, 도넛 행성, 하노이 탑

---

src/main/kotlin/jimin/62week/Coins.py
src/main/kotlin/jimin/62week/경쟁적 전염.py
src/main/kotlin/jimin/62week/최소 스패닝 트리.py
src/main/kotlin/jimin/62week/카드 섞기.py

```
Coins: ✅
경쟁적 전염: ✅ 
최소 스패닝 트리: ⛔️
카드 섞기: ⛔️
```

[이지민] - Coins, 경쟁적 전염, 최소 스패닝 트리, 카드 섞기

---

src/main/kotlin/heejik/62week/Coins.kt
src/main/kotlin/heejik/62week/경쟁적 전염.kt
src/main/kotlin/heejik/62week/최소 스패닝 트리.kt
src/main/kotlin/heejik/62week/카드 섞기.kt

```
카드섞기: ✅
경쟁적 전염: ✅
coins: ✅
최소 스패닝 트리: ❎
```

[장희직] - 카드섞기, 경쟁적 전염, coins, 최소 스패닝 트리

---

src/main/kotlin/jimin/63week/괄호 제거.py
src/main/kotlin/jimin/63week/도시 건설.py
src/main/kotlin/jimin/63week/싸지방에 간 준하.py
src/main/kotlin/jimin/63week/타일 채우기.py

```
도로 건설: ✅
싸지방에 간 준하: ⛔️
```

[이지민] - 싸지방에 간 준하, 도로 건설

---

src/main/kotlin/jimin/64week/가장 긴 증가하는 부분 수열 4.kt
src/main/kotlin/jimin/64week/내리막 길.kt
src/main/kotlin/jimin/64week/치즈.kt

```
가장 긴 증가하는 부분 수열 4: ✅
내리막 길: ⛔️
치즈: ✅ 
```

[이지민] - 가장 긴 증가하는 부분 수열 4, 치즈, 내리막 길

---

src/main/kotlin/hyunsoo/66week/맥주 마시면서 걸어가기.kt
src/main/kotlin/hyunsoo/66week/순회강연.kt
src/main/kotlin/hyunsoo/66week/용액.kt

```
용액: ✅
맥주 마시면서 걸어가기: ✅
순회 강연: ⛔️
혼자서 하는 틱택톡: ❎
```
- [문제](링크)
- [문제](링크)
```
추천: 👍  
비추천: 👎  
```
---

[전현수] - 용액, 맥주 마시면서 걸어가기, 순회강연

---

src/main/kotlin/byeonghee/week66/맥주 마시며 걸어가기.kt
src/main/kotlin/byeonghee/week66/순회강연.kt
src/main/kotlin/byeonghee/week66/용액.kt
src/main/kotlin/byeonghee/week66/혼자서 하는 틱택토.kt

```
용액: ✅
순회강연, 혼자서 하는 틱택토: ⛔️
맥주 마시면서 걸어가기: ❎
```

[소병희] - 용액, 순회강연, 혼자서 하는 틱택토, 맥주 마시면서 걸어가기
